### ISSUE TITLE
Improve SQLite support for iOS

### ISSUE THREAD

**Issue by teobugslayer** [NathanaelA/nativescript-sqlite#1]
Hi @NathanaelA,

NativeScript 1.3 introduced support for CocoaPods. is it possible to replace the manual steps for setting up the Xcode project with a podfile? You can check https://github.com/NativeScript/nativescript-cli/blob/master/CocoaPods.md for details.

**Comment by NathanaelA** [comment]
@teobugslayer, CocoaPod support is on my list of things to try to get working since this has become a MUCH easier way to do compiled plugins.   The instructions look fairly easy.  Just too many things going on, I haven't had a chance to sit down and mess with CocoaPods.

**Comment by teobugslayer** [comment]
It is just a suggestion, keep up the good work!

**Comment by NathanaelA** [comment]
@teobugslayer actually the CocoaPod idea never worked (CocoaPod couldn't be coerced into doing it properly), however, with some help from one of your coworkers Yavor Georgiev; I have a method that makes iOS install as seemless as Android!    So now their are no manual steps; just a simple install.
