### ISSUE TITLE
Is this sqlite plugin safe for multiple inserts ... multiple readers cause issue

### ISSUE THREAD

**Issue by Daxito** [NathanaelA/nativescript-sqlite#10]
Hi,
Is this sqlite plugin safe for multiple inserts? I mean, I need to insert a list of records I guess one by one, so I have a for ..each adding each record and calling the exesql function, it works (seems like) but I wonder if this is safe to do.
I had an issue reading (using db.all) where I had like four consecutive lines of code calling the db.all  selecting from 4 different tables and the last two result sets I was getting bad data back from the sql statement, my items have these properties [{id:1, name:'something'}]  I was getting back (random issue BTW, not all times but 90% of times) [{"name":1,"undefined":"something"}], very weird issue, so I had to use chaining promises instead, so I ensure I call db.all once per query and that solved the issue, but I am not sure if the insert can potentially have the same issue.

**Comment by NathanaelA** [comment]
It should be safe.  About how many rows in each of the four tables?   I'd like to create this broken test and then fix it.  db.all should be safe also...

**Comment by Daxito** [comment]
Records count is 42, 45, 689, 400 for each table, each table is just "id" and "name" columns for each.

Thanks!

**Comment by NathanaelA** [comment]
Is this on iOS or Android?   All four tables are just "id","name"?

**Comment by Daxito** [comment]
IOS, I didn't try android, the 4 tables have just two columns, Id and name, well one of them has another column but I don't think it matters.
Let me know if you need more specific info or a piece of code.

**Comment by Daxito** [comment]
There is something wrong here, just when I thought I was getting weird results back when executing reads at the same time, so now even if I execute them in sequence one by one I still get weird result back random, sometimes it works and sometimes it does not:
I get this
[{"name":6162,"undefined":"11076"},{"name":6163,"undefined":"11077"},{"name":6164,"undefined":"11078"}]

Instead of this:
[{“id”:6162,”name”:”11076"},{"name":6163,"undefined":"11077"},{"name":6164,"undefined":"11078"}]

I can provide a copy of my db, just let me know how.

**Comment by NathanaelA** [comment]
If you can send me a copy to nathan@master-technology.com; and if you could send your sql loading code that would also save me some time.

**Comment by NathanaelA** [comment]
I've pushed v1.08 - which I believe will fix this issue.   Let me know if you can still duplicate the issue.

**Comment by Daxito** [comment]
Great! I will test it asap, thank you!
BTW, do you know how to update the plug in? I mean the command, all I can see is how to install or remove but not how to update :s

**Comment by NathanaelA** [comment]
Well, the easiest way I know how, is just:
**tns plugin remove nativescript-sqlite**
then
**tns plugin add nativescript-sqlite**

This will make sure you get the newest of all the files.

**Comment by Daxito** [comment]
Yes, seems like this fixed the issue, I tested with the previous version and still the issue, then I updated to the new version I can't duplicate it anymore, thank you!
