### ISSUE TITLE
Android caches DB schema?

### ISSUE THREAD

**Issue by webleaf** [NathanaelA/nativescript-sqlite#103]
I do deleting and copying db file via `Sqlite.deleteDatabase(filepath)` and `Sqlite.copyDatabase(filepath)` on every app start.
Also on LiveSync, if my db file was changed, it `Successfully transferred` to device too.
But in fact old version of db are copied.
To get new version of db I need delete `platform` directory and run `tns run android`.
What could be the problem?

**Comment by NathanaelA** [comment]
Unfortunately I have no control over the CLI; and how it transfers things.    Are you 100% sure that even during a livesync you aren't getting the new version of the db?    I know it used to work...

**Comment by webleaf** [comment]
I thought this is not the CLI problem, because it logs in the console `Successfully transferred` for db file.
But now I've checked it one more time and looks like CLI don't transfers it in fact during livesync.

**Comment by webleaf** [comment]
@NathanaelA please, read [this](https://github.com/NativeScript/nativescript-cli/issues/4082#issuecomment-435357522)

**Comment by NathanaelA** [comment]
Ah, yeah -- I see what he is talking about.    `var myInput = _getContext().getAssets().open("app/"+name);` is pulling it out of the apk file; so no matter if it is updated or not; it is the original copy.    Guess we need to add some logic here to check the extracted directory for a more recent version...
