### ISSUE TITLE
copyDatabase path

### ISSUE THREAD

**Issue by JohanBeumer** [NathanaelA/nativescript-sqlite#110]
Is it possible to make a small adjustment in method copyDatabase in sqlite.android.js?
Now a prefilled database must be located in the projects/app folder. If it is at a different location and you pass that relative path when calling copyDatabse you get the error :
"Error: java.lang.IllegalArgumentException: File <path/to/database/db.sqlite> contains a path separator"

That is because in method copyDatabse the name of the database is determined by : 
`    if (name.indexOf('/')) {
        name = name.substring(name.indexOf('/')+1);
    }`
    
If instead of 'indexOf' 'lastIndexOf' is used, the database can be located at a different location. It is up to the programmer to pass in the correct path when calling copyDatabase.

I guess for iOS somethng simular should happen, but I can't verify that.

**Comment by NathanaelA** [comment]
Seems very reasonable.   Sure, add a PR to replace `indexOf` to `lastIndexOf` this in both ios and android; and I'll accept it and push it in the next version.  :grinning:

**Comment by NathanaelA** [comment]
Fixed in 2.2.5
