### ISSUE TITLE
SQLite security issue?

### ISSUE THREAD

**Issue by rdlauer** [NathanaelA/nativescript-sqlite#114]
Any reason to be concerned [over this notice](https://blade.tencent.com/magellan/index_en.html)?

**Comment by NathanaelA** [comment]
@rdlauer - To my knowledge the built in SQLite's doesn't support FTS3, and if they did I have no control over when the OS updates it.    

The encrypted version will use the latest version of sqlite; so it should also be good.

Thanks for letting me know about it.
