### ISSUE TITLE
IOS bugfix - Add finalize statement on execSQL

### ISSUE THREAD

**Issue by mobilemindtec** [NathanaelA/nativescript-sqlite#120]
Hi,

I'm getting an error on `db.close()`, this method return 5 - `SQLITE_BUSY` when I call `db.exeSQL`. I noticed that the `sqlite3_finalize` function is not called after execution, causing this error. So if I add this function the error is gone:

added in `sqlite.ios.js` line 367:

```
            var fresult = sqlite3_finalize(statement);

            if (fresult) {
                callback("SQLITE.ExecSQL Failed Finalize: " + fresult);
                return;
            }

```
SQLITE error code: https://sqlite.org/rescode.html#busy
SQLITE finalize: http://sqlite.org/c3ref/finalize.html
Related stackoverflow question: https://stackoverflow.com/questions/964207/sqlite-exception-sqlite-busy

Thanks!

**Comment by NathanaelA** [comment]
This has been fixed...
