### ISSUE TITLE
Problems with special characters in database

### ISSUE THREAD

**Issue by toppa80** [NathanaelA/nativescript-sqlite#121]
Hi,
I have a problem in writing special characters to the nativescript-sqlite database.
Working on iPad (iOS).

CREATE TABLE:

```javascript

const UpdatesViewModel = require("./updates-view-model");
var Sqlite = require("nativescript-sqlite");


/* ***********************************************************
* Use the "onNavigatingTo" handler to initialize the page binding context.
*************************************************************/
function onNavigatingTo(args) {
    const page = args.object;
    console.log('UPDATES');

    
    (new Sqlite("pb.db")).then(db => {
        db.execSQL("CREATE TABLE IF NOT EXISTS airports (id INTEGER PRIMARY KEY AUTOINCREMENT, icao TEXT, iata TEXT, name TEXT, city TEXT, country TEXT, lat TEXT, lng TEXT)").then(id => {
            //console.log("DB WAS CREATED:", db);
            page.bindingContext = UpdatesViewModel(db);
        }, error => {
            console.log("CREATE TABLE ERROR", error);
        });
    }, error => {
        console.log("OPEN DB ERROR", error);
    });
 
    page.bindingContext = new UpdatesViewModel();
}

exports.onNavigatingTo = onNavigatingTo;

```

This is my INSERT INTO:

```javascript
const observableModule = require("data/observable");
const Observable = require("data/observable").Observable;
var Sqlite = require("nativescript-sqlite");
//var utf8 = require ("utf8");



function UpdatesViewModel(database) {
    const viewModel = new Observable();

    viewModel.icao = '';
    viewModel.name = '';

    // INSERT INTO
    viewModel.insert = function(){            

        database.execSQL("INSERT INTO airports (icao, name) VALUES (?, ?)", [this.icao.trim(), this.name.trim()]).then(id => {
            console.log('INSERT RESULT', id);
        }, error => {
            console.log('INSERT ERROR', error);
        });
    }

    // SELECT
    viewModel.select = function(){

        database.all("SELECT * FROM airports").then(rows => {  
            for(var row in rows){
                console.log("RESULT:", rows[row][3]);
            }
        }, error => {
            console.log("SELECT ERROR", error);
        });
    }

    return viewModel;
}

module.exports = UpdatesViewModel;

```

I wann write the name "Würzburg" into the database for example.

The output is in the console.log:

![database-output](https://user-images.githubusercontent.com/5444479/52430316-1d20d580-2b06-11e9-9411-24f99a5372ea.png)

The SPECIAL CHARACTER "ü" is displayed very strange.

What is the reason for that?

Thank you very much for your help!

Best regards,
Tobias

**Comment by NathanaelA** [comment]
I just tested this in my test app; 
![image](https://user-images.githubusercontent.com/850871/52688100-79c32c80-2f1a-11e9-8ee1-3ca906c75a55.png)
And it had no problem adding, or showing either item.

**Comment by toppa80** [comment]
Thanks for your response. But do you know, what the problem could be in my case?

**Comment by NathanaelA** [comment]
1. Well console logging the value out might show differently than what the labels and text boxes show because unicode characters can be several ascii characters long per unicode character.
2. Have you tried downloading the demo source code and building and running it on your device just to verify?

**Comment by toppa80** [comment]
Ok, indeed... That was the problem. I'm really sorry, but thanks for your help. I only tested the output via console.log. An output in the UI showed the correct data!
