### ISSUE TITLE
Error when calling preparedStmt.finished()

### ISSUE THREAD

**Issue by tomjnsn** [NathanaelA/nativescript-sqlite#122]
I'm following the documentation to close a prepared statement but it is throwing an error when running on Android and calling `preparedStmt.finished()`:
```
Worker had error Uncaught TypeError: Cannot read property 'finished' of undefined
```
I can see that the records are being inserted properly. My main concern is whether I'm going to have a memory leak or cause issues with sqlite if I don't call `preparedStmt.finished()`?

I'm using 1.3.2 of nativescript-sqlite-commercial

**Comment by NathanaelA** [comment]
Please upgrade to the latest version.   :)
