### ISSUE TITLE
SQLite connections are dropped/closed on network switch

### ISSUE THREAD

**Issue by Manbearpixel** [NathanaelA/nativescript-sqlite#124]
Just started using your plugin and it's been great so far. Only issue I've encountered is that when I change the network on my phone (using an emulator Android Pixel 2) all the database connections drop/close. For example if I have mobile on and then switch wi-fi on, suddenly the previously stored db connections are empty.

This happens when switching from wi-fi to mobile, mobile to wi-fi, and no connections. This is hard for me as when the app loads I make the initial database call and pass around the connection to child models.

**Comment by NathanaelA** [comment]
@Manbearpixel - Wow, I've never heard of that issue.   Have you tried doing this on a real device and seeing if maybe it is a emulator only issue.

**Comment by Manbearpixel** [comment]
@NathanaelA I will give it a whirl when I load it on. Might try to spin this on a separate app to focus on the issue.

**Comment by Manbearpixel** [comment]
Closing this issue for now, not sure if I can replicate it. Might just be the fact that i'm passing around a bare reference to the database to better share the instance.
