### ISSUE TITLE
Performance Question: Do connections automatically close? Max connections?

### ISSUE THREAD

**Issue by Manbearpixel** [NathanaelA/nativescript-sqlite#126]
I'm curious about performance of this plugin at runtime. My key questions are:

1. Do connections close automatically after X time or if a model which has a reference to an instance is removed?
2. Is there a max number of connections to a single database table?
3. Are there performance downsides to having too many connections open to a table?

**Comment by NathanaelA** [comment]
1. Nothing closes it until you call close or the application is terminated

2. In the open source version; you should only have one connection to a database (you can pass aroudn the reference, but only one should be active).  Android & iOS doesn't have built in locking enabled, if I recall correctly.   The encrypted plugin (commercial version) is using the latest version of Sqlite compiled with all features enabled, including locking.

3. Locking can possibly cause some minor extra slowness when you are doing inserts as it has to lock things...
