### ISSUE TITLE
Error in insert command

### ISSUE THREAD

**Issue by jannomeister** [NathanaelA/nativescript-sqlite#127]
I received an error saying `SQLITE.ExecSQL Failed Prepare: 1` when executing insert statement. I'm using `nativescript-angular`. Also testing it on an iOS simulator `iPhone X`

**Comment by jannomeister** [comment]
I successfully make it work by uninstalling the app and executing `tns platform clean ios` before running it again.

**Comment by Melf11** [comment]
i had stuck for like a full day in this error and got delayed in my project.

Before you delete your XCode Workspace and before you perform a `tns platform clean ios`, open your platforms/ios/yourapp.xcworkspace and do a `Product -> Clean Build Folder`.

XCode is saving his temporary files somewhere else and if you just clean your tns stuff, the xcode build will build with temporary files.

**Comment by NathanaelA** [comment]
Interesting, I've never had an issue by just deleting the `platforms` folder; and then building again.    But thanks for the insight, it might help someone else in the future!
