### ISSUE TITLE
Create multiple table

### ISSUE THREAD

**Issue by jannomeister** [NathanaelA/nativescript-sqlite#128]
how to properly implement creating multiple table inside a `(new Sqlite("my.db"))` promise?

**Comment by NathanaelA** [comment]
```
new Sqlite(...).then( (db) => {
  db.exec(createTable).then( () => { db.exec(createAnotherTable).then...
})
```

If you have the Commercial version, it has a really really cool helper methods that allow arrays to be passed for the commands  -- where you can do:
```
new Sqlite().then( () => {
   db.exec([createTable1, createTable2, createTable3, ...]).then(() => "All Done");
});
```
