### ISSUE TITLE
Having error when using webpack

### ISSUE THREAD

**Issue by jannomeister** [NathanaelA/nativescript-sqlite#129]
Having an error when using webpack and NS v5.4

<img width="1031" alt="Screen Shot 2019-05-17 at 10 02 03 AM" src="https://user-images.githubusercontent.com/46916819/57898266-dbcd5e00-788a-11e9-8974-bf4753d0bdb3.png">

question: What line of `webpack.config.js` where I can put this code snippet? because im not using commercial version of the plugin.

```
externals: {
     'nativescript-sqlite-commercial': 'nativescript-sqlite-commercial',
     'nativescript-sqlite-encrypted': 'nativescript-sqlite-encrypted',
},
```

**Comment by NathanaelA** [comment]
That changed in 5.4 --- The next version will have updated docs.   -- This is not an error by the way; it is just a warning and doesn't break anything.

**Comment by OPADA-Eng** [comment]
@NathanaelA  Any news in this ?

**Comment by NathanaelA** [comment]
@OPADA-Eng - **It is just a warning that doesn't affect anything.**   Hence the reason I closed this already as it doesn't break anything...  And the docs here will get updated at the point I push a new version...

If you are a paid user please log into the private repo -- the docs on the private repo should already be fully up to date.  :grinning:

**Comment by rdbhagat999** [comment]
I'm using NS cli 6 with Angular 8,.I'm running into the same issue. Please update documentation on how to include externals object in webpack config.

**Comment by NathanaelA** [comment]
Well, that error appears to be coming from your app.  Your `main.ts` is referencing it and shouldn't be referencing it.
