### ISSUE TITLE
Table not found

### ISSUE THREAD

**Issue by zverbeta** [NathanaelA/nativescript-sqlite#13]
I have a problem. Some time ago, everything worked well. but now it is crashed

Error: `JS: Error: android.database.sqlite.SQLiteException: no such table: contents (code 1): , while compiling: select title from contents
JS:     android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
JS:     android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
JS:     android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
JS:     android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
JS:     android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
JS:     android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
JS:     android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
JS:     android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314)
JS:     android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1253)
JS:     com.tns.Platform.callJSMethodNative(Native Method)
JS:     com.tns.Platform.dispatchCallJSMethodNative(Platform.java:838)
JS:     com.tns.Platform.callJSMethod(Platform.java:725)
JS:     com.tns.Platform.callJSMethod(Platform.java:704)
JS:     com.tns.Platform.callJSMethod(Platform.java:694)
JS:     com.tns.gen.android.app.Fragment_ftns_modules_ui_frame_frame_l18_c45__.onCreateView(android.app.Fragment.java)
JS:     android.app.Fragment.performCreateView(Fragment.java:1695)
JS:     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:885)
JS:     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
JS:     android.app.BackStackRecord.run(BackStackRecord.java:682)
JS:     android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435)
JS:     android.app.Activity.performStart(Activity.java:5142)
JS:     android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
JS:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
JS:     android.app.ActivityThread.access$600(ActivityThread.java:141)
JS:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
JS:     android.os.Handler.dispatchMessage(Handler.java:99)
JS:     android.os.Looper.loop(Looper.java:137)
JS:     android.app.ActivityThread.main(ActivityThread.java:5103)
JS:     java.lang.reflect.Method.invokeNative(Native Method)
JS:     java.lang.reflect.Method.invoke(Method.java:525)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
JS:     dalvik.system.NativeStart.main(Native Method)`

**Comment by zverbeta** [comment]
The table in the database has 


[name_db.zip](https://github.com/NathanaelA/nativescript-sqlite/files/170772/name_db.zip)

**Comment by zverbeta** [comment]
I solved my problem, but i have a one question

What is happening with file ***.sqlite after run application? 


PS Tables find if create their through sqlite cli

**Comment by NathanaelA** [comment]
Well that depends on what you are doing.  If you use the check & copy database code, then it will copy the database to the proper location on the device so that it will be present while the app is installed (see the demo app).  If you aren't doing this; then it will create a new database (with no tables) unless you are pointing it to a specific db that already exists.   Please note on iOS a direct path to a DB might not work do to security.

**Comment by zverbeta** [comment]
My fail, I'm inattentively read the documentation
