### ISSUE TITLE
is there a way to import/export your sqlite database?

### ISSUE THREAD

**Issue by jannomeister** [NathanaelA/nativescript-sqlite#130]

**Comment by NathanaelA** [comment]
Depends on what you mean.   
- If you mean ship a database with the app; **yes** you can do that with any version.

- If you mean import some data using your app; **yes** - it is really you just reading the data and creating and running the insert statements.  Doing a select statement and writing it out.     However, the commercial version supports transactions and prepared queries which makes this a LOT LOT easier...

- If you mean upload to/download from a server; **yes**; only in the commercial version; a brand new feature is actual data replication between your local db and a server db.   You can use whatever remote db you want; you just have to write the simple JS/TS code binding to talk between them.

- If you mean you can call a function called `db.import("tableName", "myfile.tab")` or `db.export("select x,y,z from tableName", "output.tab")` then **no**; but again those should be trivial to make with the commercial version and can be made with a bit more work with the open source version.   It is a good idea for a future feature for the commercial version, though -- so thanks...  :grinning:
