### ISSUE TITLE
Drop table error

### ISSUE THREAD

**Issue by mrwrighty** [NathanaelA/nativescript-sqlite#133]
I'm calling db.execSQL("DROP TABLE categories") and getting the following error:-

SQLITE.ExecSQL Failed Prepare: 1

I can create tables and insert data but cannot drop a table.

**Comment by mrwrighty** [comment]
OK, appear to have fixed the DROP TABLE error by recoding to:-
db.execSQL("DROP TABLE IF EXISTS catagories").then(() => {db.execSQL("CREATE TABLE IF ....

**Comment by NathanaelA** [comment]
I believe the `Drop Table Categories` will ONLY work if the table actually exists!     However in the event the table does NOT exist; sqlite will fail the call like you saw...    So that is why it is safer to use the `Drop Table IF EXISTS ..` so that it will always work.  ;-)
