### ISSUE TITLE
The existing database is deleted with a new app version

### ISSUE THREAD

**Issue by Universi** [NathanaelA/nativescript-sqlite#139]
Hi,
When I increment the version of my app, the existing database is deleted, while the app is still installed (not deleted from my device).

However, I use this code :

if(!Sqlite.exists(this._dbname_user)) {     
     
           Sqlite.copyDatabase(this._dbname_user);
}
You said in another post : "If you need to keep the database, then you have to copy the db out of the app folder and into the shared storage"

Can you tell me how to do that, please?

**Comment by NathanaelA** [comment]
The above code you list should put the database in the application's database folder.

Upgrading the application should not delete the existing database. However, if you de-install your app and then install the app; the database will be deleted.

**Comment by Universi** [comment]
Yet there is something wrong.
I never de-install the app, and every time I increment my app version, the database is deleted.

**Comment by Universi** [comment]
Yet there is something wrong.
I never de-install the app and each time I increment the app version, the database is still considered non-existent and is therefore recreated. So, the database has been deleted.

**Comment by NathanaelA** [comment]
Are you are talking about development;   (i.e. tns run android) or are you talking about if the user upgrades via the store?

**Comment by Universi** [comment]
Indeed, it doesn't happen if the user upgrades on the store.
Sorry, I had never noticed that before. I got scared for nothing. I thank you so much.
I take this opportunity to thank you for the tip of the 'tns5'.
