### ISSUE TITLE
sqliteexception no such table (code 1) when selecting database

### ISSUE THREAD

**Issue by zzzxtreme** [NathanaelA/nativescript-sqlite#143]
hello there. I pre-populate an sqlite database
my nativescript will download it via http module getFile.
after download, I do these

Sqlite.exists(unique_file_name.db) = return false

Sqlite.copyDatabase(unique_file_name.db) = return true

Sqlite.exists(unique_file_name.db) = return true

after checking that it is successfully copied, I initialise the database

 new Sqlite(unique_file_name.db)  > db.isOpen() returns true

so after db.isOpen() returns true, I get some data using db.get or db.all, it gives me 

> sqliteexception no such table (code 1)

I have checked the db.file. it can be opened using DB Browser for SQLite program in windows. 

In the Pragmas tab, it reports the "User Version" as 0 (zero). Wondering if it is related

Any help would be greatly appreciated

**Comment by NathanaelA** [comment]
Have you tried the demo application?

**Comment by NathanaelA** [comment]
Please note; if you are trying to SHIP the database inside the application; you MUST update the webpack.config.js file to add your filename to the copy step.   Otherwise your database is NOT shipped in the application to be extracted at a later point.
