### ISSUE TITLE
loading performances : with workers v.s. without 

### ISSUE THREAD

**Issue by pacome2017** [NathanaelA/nativescript-sqlite#144]
I'm currently using the free version and added my workers (not at the plugin level though) so that the UI doesn't freeze, but at the cost of poor performances (100s with workers v.s. 10s without).

I found [here](https://github.com/NathanaelA/nativescript-sqlite/issues/123#issuecomment-476323260) that the speed is said to be about the same for both versions of this plugin, but on the [nativescript documentation](https://docs.nativescript.org/core-concepts/multithreading-model#general-guidelines) it is said that workers can be slower in some cases.

Did someone already experienced this issue ? And did upgrading to the commercial version solved it ?

**Comment by NathanaelA** [comment]
In all my tests of my commercial worker versions; the speed difference is not really any slower.    It is fairly negligible.  

If your main thread is doing a lot of work while the background thread is also doing a lot of work; it will of course be affected, as more load on the device effects all threads.

If your main thread is just doing animations (or nothing) while waiting for the data from the worker, then the speed should be very similar as if you ran it on the main thread.
