### ISSUE TITLE
how to get the .db file to view in laptop / PC

### ISSUE THREAD

**Issue by SolFoxu** [NathanaelA/nativescript-sqlite#145]
i'm having a problem finding the .db file to select / view the data in my PC 

i'm using android nativescript-vue

BTW thank you for the plugin it's awe some :)

**Comment by NathanaelA** [comment]
There are two ways to do it.  
1. Ship the db with the app; and use copyDatabase to install it properly.
2. Create the database on the device

**Comment by SolFoxu** [comment]
> There are two ways to do it.
> 
> 1. Ship the db with the app; and use copyDatabase to install it properly.
> 2. Create the database on the device

that's mean for the first option , i created a sqlite db file and copy the database from my NS app?
and for the second option i'm not sure hot to create the database inside the device , do i run the create database command in the sqlite when i run the init?

**Comment by SolFoxu** [comment]
> There are two ways to do it.
> 
> 1. Ship the db with the app; and use copyDatabase to install it properly.
> 2. Create the database on the device

still can't get the db file after folowing the first option, what i mean is i can get the .db inside my device file manager, is there any way to do that kind of thing?

**Comment by NathanaelA** [comment]
The demo app shows how to ship databases with the application.  :grinning:
