### ISSUE TITLE
Sqlite.exists not working

### ISSUE THREAD

**Issue by akwatra** [NathanaelA/nativescript-sqlite#146]
Sqlite.exists( dbname ))... not working,

and var = dbname same work for new Sqlite(dbname, function(err, dbc) { ...

**Comment by NathanaelA** [comment]
Nothing has changed with the `.exists` so it should still be working. 

However their are a couple things that I can think of that can cause you potentially issues.
1. Are you sure that you have in your webpack config copying of the sqlite files.  If you have upgraded you might not be copying the files you need.
2. What Android OS, the latest Android you might need to enable the legacy file access.
