### ISSUE TITLE
json_object Not available

### ISSUE THREAD

**Issue by noonenew** [NathanaelA/nativescript-sqlite#148]
Dear Can you assist me I am tring to use json object but the error message says  [Error: android.database.sqlite.SQLiteException: no such function: json_object (code 1): , while compiling: 

```
SELECT json_object('TimeSheetAppId',t.Id,'TaskDate',
t.TaskDate,'Description',t.Description,'Duration',t.Duration,'UserName',t.UserName,'ProjectId',t.ProjectId,'DepartmentId',t.DepartmentId,'DepartmentName',tsd.Eng_name,'ActivityId',t.Activit
yId,'TaskCategoryId',tsc.ParentId,'TaskSubCategoryId',t.TaskSubCategoryId,'MISUserId',t.MISUserId,'EMPUserId',t.EMPUserId,'IsSynced',t.IsSynced,'IsModified',t.IsModified,'IsDeleted',t.IsDel
eted,'TimeSheetTaskRefs',(SELECT JSON_ARRAY(GROUP_CONCAT( json_object('TimeSheetAppId',Id,'TimeSheetAppParentId',ParentId,'EmployeeId',EMPUserId,'IsDeleted',IsDeleted))) FROM ReferenceTasks
 where ParentId = t.Id)) FROM TimeSheet AS t INNER JOIN TaskCategories AS tsc ON tsc.Id = t.TaskSubCategoryId INNER JOIN DepartmentsList AS tsd ON tsd.Id = t.DepartmentId INNER JOIN Project
s AS p ON t.ProjectId = p.Id WHERE IFNULL(t.IsSynced,0)=0]

```

**Comment by NathanaelA** [comment]
JSON_Object is not part of normal sqlite libraries included in Android/iOS:
It is an extension -- https://www.sqlite.org/json1.html  

To use this; you would have to use the commercial/encrypted version which I believe has the extra extensions compiled in.

HOWEVER, with that said -- I don't understand why you can't just eliminate the JSON_ARRAY/JSON_OBJECT in your query and then the result set you get back in NativeScript you can just send it to the JS command JSON.stringify...
```
const results = sqlite.getAll(....)....
const jsonresults = JSON.stringify(results);
```

**Comment by noonenew** [comment]
Der Nathanael,
Thank you for your reply,

The thing is I will not be using the selection results in Nativescript, all the results generated will be sent to a server online to be synced, Like so

```
timeSheetApp:{
TimeSheetAppId:TimeSheetAppId,
MISUserId:MISUserId,
ProjectId:ProjectId,
ActivityId:ActivityId,
TaskCategoryId:TaskCategoryId,
TaskSubCategoryId:TaskSubCategoryId,
DepartmentId:DepartmentId,
DepartmentName:DepartmentName,
TaskDate:TaskDate,
Description:Description,
Hours:Hours,
Minutes:Minutes,
IsModified:IsModified,
IsDeleted : IsDeleted,
TimeSheetTaskRefs:[
{TimeSheetAppId:TimeSheetAppId,TimeSheetAppParentId:TimeSheetAppParentId,EmployeeId:EmployeeId,Attached:true},
{TimeSheetAppId:TimeSheetAppId,TimeSheetAppParentId:TimeSheetAppParentId,EmployeeId:EmployeeId,Attached:false}
]
}

```

So I thought that JSON object will help me to eliminate the repeated value when fetching data from one to many relations.

**Comment by NathanaelA** [comment]
You can easily use the .all/.each/.get commands to get the records and then create the object you need in memory; then use `json.stringify` to turn it into a json object you can send to the server.    

Otherwise your only other choice is to use the commercial/encrypted version, which does have all the additional extensions compiled in.
