### ISSUE TITLE
Error: java.io.FileNotFoundException: app/name_db.sqlite

### ISSUE THREAD

**Issue by mengineer10** [NathanaelA/nativescript-sqlite#149]
Hi, I didn't change anything in code. Just I downloanded and ran the project. But I got that error "Error: java.io.FileNotFoundException: app/name_db.sqlite".
There is database in F:\ProjectsNativescript\nativescript-sqlite\demo\app\ folder. But I got this error.

name_db.sqlite's path on my machine is F:\ProjectsNativescript\nativescript-sqlite\demo\app 
I didn't change anything on project.
Hey there, please, can you help me?

An uncaught Exception occurred on "main" thread.
Calling js method onCreateView failed
Error: java.io.FileNotFoundException: app/name_db.sqlite
    android.content.res.AssetManager.openAsset(Native Method)
    android.content.res.AssetManager.open(AssetManager.java:313)
    android.content.res.AssetManager.open(AssetManager.java:287)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
    com.tns.Runtime.callJSMethod(Runtime.java:1109)
    com.tns.Runtime.callJSMethod(Runtime.java:1089)
    com.tns.Runtime.callJSMethod(Runtime.java:1081) .....

**Comment by NathanaelA** [comment]
I assume something probably replaced the webpack config in the demo; did you run a TNS update/migrate command?   
---
Typically if this happens, it means the webpack config isn't including the .sqlite files.   By default it doesn't.   You need to edit the webpack.config.js and add towards the bottom the glob for **/*.sqlite
```
           new CopyWebpackPlugin([
                { from: { glob: "fonts/**" } },
                { from: { glob: "**/*.jpg" } },
                { from: { glob: "**/*.png" } },
                { from: { glob: "**/*.sqlite" } },
```
By default it has the first 3 lines, you just add the fourth; then re-run the project.
