### ISSUE TITLE
Execute multiple SQL in a transaction

### ISSUE THREAD

**Issue by andycwwai** [NathanaelA/nativescript-sqlite#15]
Hi, thanks for providing this plugin. It's simple to use.
I would like to know how to implement transaction using this plugin, such that we can control commit/rollback when executing a batch of SQLs. Any recommendation is appreciated. Thanks.

**Comment by NathanaelA** [comment]
You should be able to just do a simple:
```
    sql->execute('begin transaction') 
    /* do all my other sql calls */   
    sql->execute('commit');   // or rollback
```
Unless, I'm missing understanding the question...

**Comment by andycwwai** [comment]
Thanks for your reply.
What's "sql" in your example?
For example I would like to execute a transaction of SQLs after getting a db connection:
let sqlite = require("nativescript-sqlite");
new sqlite("test.db", function(err, dbConn) {
    dbConn.???
});
How to achieve this? Thanks.

**Comment by NathanaelA** [comment]
Sorry for the delay, yes, dbConn would be the it in your example.   

However, if someone wanted to add the actual transaction command to the driver I would accept the pull request once we have a version for both iOS and Android..

**Comment by NathanaelA** [comment]
Just a FYI: this feature has now been added to the commercial version of sqlite -- in addition the code I wrote supports nested transactions, where my example above does not.
