### ISSUE TITLE
Not able to send data to post call

### ISSUE THREAD

**Issue by rhushi-lokhande** [NathanaelA/nativescript-sqlite#150]
I am working on an Angular Nativescript app. In which I am trying to post data to the server but it always sending the **blank body** to the server when I preview it with **nativescript preview** app. Here is my service function.
```
register(data) {
    console.log(this.regUrl)
    return this.http.post(this.regUrl, data, { headers: new HttpHeaders({ 'Content-Type': 'application/json' }) });
  }
```

here is my dependancy 
```
"dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nativescript/theme": "~2.2.1",
    "nativescript-angular": "~8.20.3",
    "nativescript-appavailability": "^1.3.2",
    "nativescript-phone": "^1.4.1",
    "nativescript-social-share": "^1.6.0",
    "nativescript-sqlite": "^2.3.3",
    "nativescript-toast": "^2.0.0",
    "nativescript-ui-sidedrawer": "~8.0.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "~6.3.0",
    "zone.js": "~0.9.1"
  },
```

**Comment by NathanaelA** [comment]
The NativeScript-Preview app has several limitations.   Most compiled plugins (like NS-Sqlite) don't work in the Preview app.   To my knowledge the preview app does NOT have sqlite compiled in.

**Comment by rhushi-lokhande** [comment]
Its was working in the preview app, I have just cleared my storage and then tried. I was causing another issue.  While making an HTTP call to server my post data always blank when it goes to the server.
