### ISSUE TITLE
copy database with different source and target names.

### ISSUE THREAD

**Issue by bobvann** [NathanaelA/nativescript-sqlite#151]
It would be very useful to have a method to copy the database from a source file and then save it to the right directory, but with a different name.

At the moment, if I run copyDb('mydbname') it searches for the db with the given name and then the copied db will have the same name.

The scenario is the following: I have some sqlite databases stored online. When user picks one, it downloads it and the run copyDb to copy it to the app directory.

I can provide a pull request for this.

**Comment by NathanaelA** [comment]
I love PR's.    :-D

**Comment by bobvann** [comment]
https://github.com/NathanaelA/nativescript-sqlite/pull/153

**Comment by NathanaelA** [comment]
v2.6.0 has the changes to copyDatabase that your PR inspired.  :D
