### ISSUE TITLE
How to change results type to Sqlite.RESULTSASOBJECT

### ISSUE THREAD

**Issue by thamibn** [NathanaelA/nativescript-sqlite#154]
Hi how can i change my results type from Sqlite.RESULTSASARRAY to Sqlite.RESULTSASOBJECT

example code.
```
init(context) {
      (new Sqlite("my.db")).then(db => {
        db.execSQL("CREATE TABLE IF NOT EXISTS people (id INTEGER PRIMARY KEY AUTOINCREMENT, firstname TEXT, lastname TEXT, details TEXT)").then(id => {
          context.commit("init", { database: db });
        }, error => {
          console.log("CREATE TABLE ERROR", error);
        });
      }, error => {
        console.log("OPEN DB ERROR", error);
      });
    },
```

please advice where can i put the configuration on the above example code

nativescript-vue, vuex and nativescript-sqlite

**Comment by stefalda** [comment]
Check the documentation for DB.resultType()

Parameters
Pass in Sqlite.RESULTSASOBJECT or Sqlite.RESULTSASARRAY to change the result sets configuration This will set the database to return the results in which ever choice you make. (Default is RESULTSASARRAY)

**Comment by thamibn** [comment]
@stefalda please share the documentation link.

and i would highly appreciate to show an example.  or twick the above code for direction.
thanks

**Comment by thamibn** [comment]
Thank you very much @stefalda 
twicked my code as follows and its working perfect.

```
init(context) {
      (new Sqlite("my.db")).then(db => {
        db.resultType(Sqlite.RESULTSASOBJECT);
        db.execSQL("CREATE TABLE IF NOT EXISTS people (id INTEGER PRIMARY KEY AUTOINCREMENT, firstname TEXT, lastname TEXT, details TEXT)").then(id => {
          context.commit("init", { database: db });
        }, error => {
          console.log("CREATE TABLE ERROR", error);
        });
      }, error => {
        console.log("OPEN DB ERROR", error);
      });
    },
```
