### ISSUE TITLE
Run ATTACH command?

### ISSUE THREAD

**Issue by RayburnTrading** [NathanaelA/nativescript-sqlite#155]
Hi,

Is there a way to use the sqlite ATTACH command to join two separate databases?

https://stackoverflow.com/questions/6824717/sqlite-how-do-you-join-tables-from-different-databases

Thanks.

**Comment by NathanaelA** [comment]
Sorry have no idea if the open source version can do this as it uses the native implementation of sqlite on the phone and I have never have tried.   Download the demo, add a second db and try...  :grinning:

However, I am pretty sure the encrypted commercial version can; as the SQLite driver for the encryption has pretty much every single feature turned on...
