### ISSUE TITLE
demo doest work on iOS 

### ISSUE THREAD

**Issue by mirozahorak** [NathanaelA/nativescript-sqlite#156]
LOG from device iPhone XS 64GB: 
CONSOLE LOG file:///app/bundle.js:1273:15: SQLITE.ALL - Prepare Error 11
LOG from device iPhone XS 64GB: CONSOLE LOG file:///app/bundle.js:421:20: !!! SQLITE.ExecSQL Failed Prepare: 11 insert into names (name) values (?)
LOG from device iPhone XS 64GB: CONSOLE LOG file:///app/bundle.js:421:20: !!! SQLITE.ExecSQL Failed Prepare: 11 insert into names (name) values (?)
LOG from device iPhone XS 64GB:

**Comment by NathanaelA** [comment]
@mirozahorak - Was there any errors before this?    
Real device or Simulator?

**Comment by NathanaelA** [comment]
In case people see this issue, my guess is they didn't have a db open or created.    I have tested the code many times since this point on iOS and Android.
