### ISSUE TITLE
Multiple documentation issues (and one real)

### ISSUE THREAD

**Issue by emirotin** [NathanaelA/nativescript-sqlite#159]
Being completely new to NS I had several issues getting this module to work. I thought I would share them if you want to make getting started easier.

1) `const Sqlite = require( "@proplugins/nativescript-sqlite" );` wouldn't work, the name of the module is unscoped `nativescript-sqlite`. Also there's no mention of the npm module install in the docs. I'm using svelte-native where I'm not dealing with `tns` to install dependencies, I'm directly using npm/yarn.

2) `import {Sqlite} from "@proplugins/nativescript-sqlite";` has another issue, `Sqlite` is the default export, not a named one, it should be `import Sqlite from "nativescript-sqlite";`

3) It's quite unconventional in my experience for the constructor to return a Promise resolving to the actual object. I'm speaking about the code like this when using Promises:
```javascript
const dbPromise = new Sqlite("MyTable");
const db = await dbPromise;
```

A more straightforward approach could be to attach a promise to the DB itself:

```javascript
const db = new Sqlite("MyTable");
await db.ready; // <-- this is a promise that resolves to nothing (or null, or true)
// use `db` securely here
```

Also, it's just as unusual to accept a callback in a constructor. I personally would just drop the whole "constructor" thing and make `Sqlite` a factory function.

4) Also the official example
```
const db_promise = new Sqlite("MyTable", function(err, db) {
    if (err) {
      console.error("We failed to open database", err);
    } else {
      // This should ALWAYS be true, db object is open in the "Callback" if no errors occurred
      console.log("Are we open yet (Inside Callback)? ", db.isOpen() ? "Yes" : "No"); // Yes
    }
});
```

goes directly against your own advice not to mix callbacks and promises in the same codebase (which is definitely correct advice). This code is hard to perceive and it also leaves an impression the callback is mandatory even when using Promises.

5) The `version` method is supposed to return a _number_, at least that would make the max sense. But it is actually returning _an array_. Your code example `if (ver === 0)` wouldn't work though if you're using non-strict equality (which is widely considered a bad part of the language) it will work (because `[0] == 0` due to JS type coercion quirks).

**Comment by NathanaelA** [comment]
Hi Thanks for all the AWESOME feedback.  :-)

> const Sqlite = require( "@proplugins/nativescript-sqlite" );

This is a mistake; I was going to move sqlite to @proplugins namespace, and even had it fully working under that namespace, but then just before I moved it, I realized that it could break a lot of clients.   So I reverted all those changes.     Looking at the docs, it looks like I missed that one, I'll get that fixed.  :grinning: 

> import {Sqlite} from "@proplugins/nativescript-sqlite";

Good catch, I totally glossed over that one.

>const dbPromise = new Sqlite("MyTable");
const db = await dbPromise;

You can actually do, without the `new`:  ;-)  
const db = await Sqlite("MyTable");   

I updated the docs.  :grinning:

>4. Also the official example

This was more for simplicity that I joined the two examples; but I can see your point so I turned it into two separate code snippets.  :grinning: 

>5. Version, under a callback, it does return a number.   However, looking at the code path I believe you are correct under a promise it will return the value array...   Good catch, I've never noticed that discrepancy...

It will be fixed in the next version to be a number under both path's.

**Comment by emirotin** [comment]
JFYI I've checked it and the version is fixed indeed in 2.6.2.

`const db = await Sqlite(dbName);`
doesn't work though while
`const db = await new Sqlite(dbName);`
works fine (yet looks weird 😄)

**Comment by NathanaelA** [comment]
Weird, the `await sqlite` should be working ; I'll run a test...  :)

Nathanael A.

**Comment by NathanaelA** [comment]
Should be working fine in 2.6.3, had a silly `if` order precedence bug...
