### ISSUE TITLE
Prepared Statements

### ISSUE THREAD

**Issue by nicHoch** [NathanaelA/nativescript-sqlite#16]
Hi Nathanael

thanks for the nice plugin.
Is there a way to use prepared statements?

Nicky

**Comment by NathanaelA** [comment]
Nicky, nope -- at this point I never exposed the prepare statement api.

I am not at all opposed to this plugin having this feature and either someone else can add a pull request for it; or I might add it at some point in the future when I (or a some client) needs it.

**Comment by NathanaelA** [comment]
Prepared statements are now part of the commercial offering.  Thank you for your enhancement request.
