### ISSUE TITLE
execSql weird error handling

### ISSUE THREAD

**Issue by jscti** [NathanaelA/nativescript-sqlite#160]
Hi, how am i supposed to handling error (example: while giving execSQL a wrong SQL request) ?

Seems like execSQL returns a promise (so I should be able to catch a rejection) but the `console.log("!!!", err, sql);` swallows silently all errors (sqlite.ios.js line 414).

So I use the callback but it's kind of ... strange.. :
```typescript
return new Promise((resolve, reject) => {
    db.execSQL(query, err => {
        if (err) return reject(err);
        resolve();
    }) 
});
```

Am i missing something ?

Thanks

**Comment by NathanaelA** [comment]
Nice catch, I must have put that in while debugging something, and totally screwed up by not removing it.   Thank you for pointing that out!    This will be fixed in the next version.
