### ISSUE TITLE
Upgrade to Nativescript 7

### ISSUE THREAD

**Issue by JWiseCoder** [NathanaelA/nativescript-sqlite#164]
The code in this project is not up to date with current Nativescript practices (e.g. there are imports that use tns-core-modules).  Are there any plans to update this in the near future?  (For the record, this plugin currently does appear to work in NS 7.)

**Comment by NathanaelA** [comment]
The plugin does work fine with NS7, the demo app has not been updated yet as it is a fairly low priority, but at some point will be.

**Comment by JWiseCoder** [comment]
Thanks.  Sorry to bother about it.  I just wanted to be sure it was future-proof.  It is a very good plugin, and I rely on it quite a bit.
