### ISSUE TITLE
Commercial License

### ISSUE THREAD

**Issue by bytelabsco** [NathanaelA/nativescript-sqlite#168]
Is there a copy of the commercial license that's publicly available?  We want to purchase a commercial license, but would like to review the licensing agreement before making that purchase.  It's not listed on the nativescript.tools website.

**Comment by NathanaelA** [comment]
Thanks for letting me know, I'll have to add a FAQ entry.  ;-)  

License text is very simple:
```

	NativeScript-Sqlite-commercial
	Copyright (c) 2016-2021, Nathanael Anderson

	If you have purchased this plugin, then you have the rights to use it in any type of application(s)
	that you have built.   Each developer on the team working on an app with this plugin needs to have
	a valid license.

	You MAY NOT sub-license this.  So, if you have a customer that you need to provide the full source to;
	then they will need a valid licensed copy of this plugin.

	You MAY NOT release the plugin source in any public venue.  So please if you need to commit this code;
	use a private repo.

	You MAY include this in any number of applications.

	You MAY put this plugin on as many computers as needed; including build servers, etc...
```

**Comment by NathanaelA** [comment]
Basically in summary, each dev that is working on the project that contains it needs to have a license.   It is not licensed to devices, or apps.   Build Servers/CI servers/etc do not need license.

I've added the text to the FAQ thanks for letting me know.

**Comment by bytelabsco** [comment]
Thank you for the quick response.  Do you offer or plan to offer any sort of site/enterprise license?  We have several dev teams who are working on various NS apps, and teams will often be shuffled around.  Additionally one team may later have to support or modify code another team developed, so having some sort of enterprise license will ensure we stay compliant without having to manage individual licenses.

**Comment by NathanaelA** [comment]
Send me an email at nathan@master-technology.com and yes we can work out a site license.
