### ISSUE TITLE
What needs to be modified when working with nativescript 8 ?

### ISSUE THREAD

**Issue by shilik** [NathanaelA/nativescript-sqlite#169]
Hi, Thanks for the great plugin.It works well with nativescript 7 & 6 with some modifications needed for webpack.config.js.

@nativescript/webpack version 5.0.0 has a minimal setting as the following. What needs to be done to make nativescript-sqlite work with @nativescript/webpack 5?

`const webpack = require("@nativescript/webpack");

module.exports = (env) => {
  webpack.init(env);

  return webpack.resolveConfig();
};
`

**Comment by NathanaelA** [comment]
It should already work with NS8.   What error are you getting?

**Comment by shilik** [comment]
Well, I am not familiar with webpack setting, so the main point is how to
put something like

 new CopyWebpackPlugin([
                { from: { glob: "fonts/**" } },
                { from: { glob: "**/*.jpg" } },
                { from: { glob: "**/*.png" } },
                { from: { glob: "**/*.sqlite" }},
            ], { ignore: [`${relative(appPath, appResourcesFullPath)}/**`] })

in the new webpack 5.

**Comment by NathanaelA** [comment]
Ah, the newly release 2.7.0 will work with NS 8 (& before) and has automatic webpack 5 rules so you don't have to do a thing....
