### ISSUE TITLE
Got resultSet of 'undefined' after upgrading to NS 8

### ISSUE THREAD

**Issue by shilik** [NathanaelA/nativescript-sqlite#170]
The following codes work well in NS 7,but yield 'undefined' result.
What could be the reasons?

`    const dbNameToeic = "test_db.sqlite";
      await new sqlite(dbNameToeic, function (err, db) {
        console.log("Is a Sqlite Database:", sqlite.isSqlite(db) ? "Yes" : "No");
        // Should print "Yes"
        console.log("Are we open yet (Promise based)? ", db.isOpen() ? "Yes" : "No");
        // Yes
        var word = "interesting";
        db.resultType(sqlite.RESULTSASOBJECT);
        var query_word = word.toLowerCase();
        db.all("SELECT * FROM cmu_ipa WHERE word =?", [word], function (err, resultSet) {
          console.log("The record row is:", resultSet);
        });
      });`

details of the package.json is:
  "dependencies": {
    "@nativescript-community/texttospeech": "^3.0.3",
    "@nativescript/core": "^8.0.1",
    "@nativescript/theme": "^3.0.1",
    "@nstudio/nativescript-cardview": "^2.0.1",
    "@nstudio/nativescript-loading-indicator": "^4.1.0",
    "@triniwiz/nativescript-toasty": "^4.1.3",
    "axios": "^0.21.1",
    "chinese-to-pinyin": "^1.3.1",
    "cldr-segmentation": "^2.2.0",
    "fast-xml-parser": "^3.19.0",
    "franc": "^5.0.0",
    "furigana": "^0.19.3",
    "gem-furigana": "^1.0.9",
    "german-dict-helper": "^3.1.9",
    "google-tts-api": "^2.0.2",
    "he": "^1.2.0",
    "iskanji": "^1.0.3",
    "nativescript-audio": "^6.2.4",
    "nativescript-exit": "^1.0.1",
    "nativescript-menu": "^1.1.7",
    "nativescript-sqlite": "^2.7.0",
    "nativescript-tailwind": "^2.0.1",
    "nativescript-toasty-ns-7": "^14.0.0",
    "nativescript-ui-chart": "^8.0.2",
    "nativescript-vue": "^2.9.0",
    "nativescript-windowed-modal": "^7.0.0",
    "node-polyfill-webpack-plugin": "^1.1.0",
    "tailwindcss": "^2.1.1",
    "traditional-or-simplified": "^1.0.3",
    "vue-axios": "^3.2.4",
    "vuex": "^3.6.2",
    "wanakana": "^4.0.2",
    "wink-pos-tagger": "^2.2.2",
    "zh_cn_zh_tw": "^1.0.7"
  },
  "devDependencies": {
    "@babel/core": "~7.13.15",
    "@babel/preset-env": "~7.13.15",
    "@nativescript/android": "8.0.0",
    "@nativescript/ios": "8.0.0",
    "@nativescript/webpack": "~5.0.0-beta.9",
    "babel-loader": "~8.2.2",
    "nativescript-vue-template-compiler": "^2.9.0",
    "node-sass": "^4.14.1",
    "vue-loader": "~15.9.6"
  },

**Comment by NathanaelA** [comment]
Is the resultSet undefined, or some other line printing undefined?       I've run the sqlite demo & tests under ns8 and everything passed, it should be working correctly under ns8.  Off the top of my head the only thing I can think of is did you copy your `test_db.sqlite`  database over to the new app, or is it possible it has a empty table?

**Comment by shilik** [comment]
Well,my bad. the resultSet got data from db after adding if(err){console.log(err)} in the code.
Thanks for your reply.
``db.all("SELECT * FROM cmu_ipa WHERE word =?", [word], function (err, resultSet) { 
if(err){
console.log(err);
}else{
console.log("The record row is:", resultSet); }); });

**Comment by NathanaelA** [comment]
So you are all good?

**Comment by shilik** [comment]
Yes, it is back to normal again! Thank you very much.
