### ISSUE TITLE
ORM compatible

### ISSUE THREAD

**Issue by leocaseiro** [NathanaelA/nativescript-sqlite#19]
First of all, many thanks for this amazing Library.

I was wondering if there's any ORM or Query Builder library that would be compatible with NativeScript SQLite such as [Knex.js](http://knexjs.org/), [Sequelize.js](http://docs.sequelizejs.com/en/latest/) or [node-sql](node-sql)

Anyone have used?

Thanks

**Comment by NathanaelA** [comment]
@leocaseiro Sorry, I haven't not used any of those ORM / Query Builder libraries.  So I couldn't say if they would work with it.     But yeah a cool query builder library would be pretty cool.  Let me know if you find one...

**Comment by leocaseiro** [comment]
Thank you for your reply. I'd say that I'm not having much luck.

Most of these libraries depend on a lot of node...or third-party libraries. I'm not sure If I'm doing something wrong or they really won't work...

**Comment by leocaseiro** [comment]
UPDATE: I'm just tested the [squel](https://github.com/hiddentao/squel) and it works great.

It's my first time using it but seems work much better than just write your queries. Also to update and [insert](https://github.com/hiddentao/squel#insert), you can use objects. sounds promising

**Comment by leocaseiro** [comment]
PS: I've just noticed the sample-Tasks uses something called Everlive. It seems from Telerik internal use, but the syntax of [Everlive.Query](https://github.com/NativeScript/sample-Tasks/blob/master/app/utils/service.ts#L236) it's quite similar to [Squel](https://hiddentao.github.io/squel/#expressions)

**Comment by terreb** [comment]
@leocaseiro Thank you for your insight with regards to squel! Have you had any issues with it so far? Or probably you have found a better alternative?

**Comment by leocaseiro** [comment]
Hi @terreb, it worked very well. You should try it.

**Comment by terreb** [comment]
Hi @leocaseiro thank you for your instant reply! 've been looking for something more advanced like [Sequelize](http://docs.sequelizejs.com/en/v3/) where I can define models and probably tie them somehow to Natavescript view-models.

**Comment by leocaseiro** [comment]
Hi @terreb, I've tried to setup `Sequelize`, as well as some other libraries such as [node-orm2](https://github.com/dresende/node-orm2), `Knex`, `node-sql` and so on. However, I didn't manage to work.

I am currently focus on an app which doesn't need SQLite, so I stopped trying.

Please let me know if you get succeed in your attempts. I'll be very interested in trying it out.

Thanks

**Comment by terreb** [comment]
@leocaseiro ok sure, I will let you know if found something decent. Btw, have you already tried [LokiJS](https://www.npmjs.com/package/nativescript-loki)?

**Comment by leocaseiro** [comment]
No! I haven't....

**Comment by ZainShaikh** [comment]
Is there any update on this feature?

**Comment by Sharique-Hasan** [comment]
@terreb Did you try Sequelize?

**Comment by leocaseiro** [comment]
Quick update. it seems TypeORM is the way to go... https://github.com/typeorm/typeorm/issues/548

**Comment by championswimmer** [comment]
Added nativescript support here #2407

review appreciated :)

**Comment by wendt88** [comment]
After 2 days of work I was able to run it with knex!

**Comment by Jarwain** [comment]
@wendt88 Did you have to do anything special to get it working with knex?

**Comment by wendt88** [comment]
I had to make knex webpack-ready with a own [webpack configuration](https://docs.nativescript.org/tooling/custom-webpack-configuration):
```
const webpack = require("webpack");
const path = require("path");
const webpackConfig = require("./webpack.config");

module.exports = (env) => {
    const config = webpackConfig(env);

    config.externals
        .push({
            'formidable': 'url',
            'sqlite3': 'sqlite3',
            'mariasql': 'mariasql',
            'mssql': 'mssql',
            'mssql/lib/base': 'mssql/lib/base',
            'mssql/package.json': 'mssql/package/json',
            'mysql': 'mysql',
            'mysql2': 'mysql2',
            'tedious': 'tedious',
            'oracle': 'oracle',
            'strong-oracle': 'strong-oracle',
            'oracledb': 'oracledb',
            'pg': 'pg',
            'pg-query-stream': 'pg-query-stream',
        });

    config.resolve.alias.crypto = 'crypt';
    config.resolve.alias.timers = '@nativescript/core/timer';
    config.resolve.alias['../migrate/Migrator'] = path.resolve(__dirname, './app/helpers/knex/fake');
    config.resolve.alias['../seed/Seeder'] = path.resolve(__dirname, './app/helpers/knex/fake');

    config.node.net = 'empty';
    config.node.tls = 'empty';
    config.node.console = true;

    config.plugins
        .push(
            new webpack.DefinePlugin({
                'process.version': JSON.stringify(process.version),
                'process.stderr': JSON.stringify(process.stderr)
            })
        );
    return config;
}
```
it does NOT work with migrations and seeds. i meda a `fake.js` to replace those classes:
`./app/helpers/knex/fake.js`:
```
module.exports = {};
```

then i created a custom driver with `nativescript-sqlite`:
```
class Sqlite {
    constructor (dbName, fn) {
         this.db = new Sqlite(dbName)
             .then(db => {
                 fn();
                 return db;
              });
    }
    get (sql, bindings, callback) {
        this.db.get(sql, bindings).then(result => callback(undefined, result), error => callback(error))
    }
    all(sql, bindings, callback) {
        this.db.all(sql, bindings).then(result => callback(undefined, result), error => callback(error))
    }
    run(sql, bindings, callback) {
        this.db.execSQL(sql, bindings).then(result => callback(undefined, result), error => callback(error))
    }
}
```

ant here I get the knex instance:
```
const Dialect = require('knex/lib/dialects/sqlite3/index.js');
Dialect.prototype._driver = () => require('./driver'); // the file above
knex({
    client: Dialect,
    useNullAsDefault: true,
    connection: {
        filename: dbName
    }
});
```

it works for me on `node 12`, `"nativescript-sqlite": "^2.6.4"` and `"knex": "^0.21.5"`
