### ISSUE TITLE
Please, improve documentation for RESULTSASOBJECT

### ISSUE THREAD

**Issue by leocaseiro** [NathanaelA/nativescript-sqlite#20]
Hi, I'm not sure why `RESULTSASOBJECT` is the default FETCH, as I believe 99% of users would expect objects and not arrays.

Anyway, I took a while to understand that was a function and not a parameter. So that would be nice an example. So here we go:

```javascript
if (!Sqlite.exists('database.db')) {
    Sqlite.copyDatabase('database.db');
}
(new Sqlite('database.db')).then(function(db) {
        
    db.resultType(Sqlite.RESULTSASOBJECT); //Here where the magic happens

    db.execSQL("CREATE TABLE IF NOT EXISTS table (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT)").then(function() {
        pageData = viewModel(db);
        page.bindingContext = pageData;
    }, function(error) {
        console.log("CREATE TABLE ERROR", error);
    });
}, function(error) {
    console.log("OPEN DB ERROR", error);
});
```

> If you are doing `db.resultType = Sqlite.RESULTSASOBJECT` you are doing wrong.

**Comment by NathanaelA** [comment]
Documentation has been updated.  Thanks.

**Comment by tareq89** [comment]
Thanks, saved me time on understanding how it works.
