### ISSUE TITLE
Cannot find module 'nativescript-sqlite'

### ISSUE THREAD

**Issue by jahidshohel** [NathanaelA/nativescript-sqlite#24]
I am trying an app with "Nativescript+Typescript+NG2". Here is how my `package.json` dependencieslooks like -

` "dependencies": {
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/http": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/platform-server": "2.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.1",
    "nativescript-angular": "0.1.1",
    "nativescript-sqlite": "^1.0.10",
    "tns-core-modules": "2.0.0"
  }`

And my code looks like -

`import {Sqlite} from "nativescript-sqlite";`

But I am getting this error -

`app/pages/actionbar/tabs/db/db.service.ts(3,22): error TS2307: Cannot find module 'nativescript-sqlite'.`

I was trying on Android. Any idea why I am getting that error?

**Comment by NathanaelA** [comment]
Sorry, I missed this question.   I suspect because there are not typings.  Can you try a simple:
`let sqlite = require('nativescript-sqlite');`  and see if that works?
Also after any added plugins you have to rebuild the app; if you are using the tns livesync mode; it doesn't sync plugins.

**Comment by NathanaelA** [comment]
Closed due to inactivity

**Comment by carlosdelfino** [comment]
I tried to use the suggested way in the file `d.ts` and it was not accepted informing:

![image](https://user-images.githubusercontent.com/369056/33583175-bb005d88-d937-11e7-902d-8e47f43f2b1b.png)

and even if I declare a module to contain the `required`, it does not accept that the value returned by the `required` function is assigned.

but, in normal `ts`file work fine.
