### ISSUE TITLE
sqlite.copyDatabase()

### ISSUE THREAD

**Issue by abhisekgithub** [NathanaelA/nativescript-sqlite#26]
Hi, 
As per the documentation I have my testdb.db file inside the app folder. and when I am trying to execute the code sqlite.copyDatabase('testdb.db') it throws error.
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.groceries/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method getActivity failed

Error: 
Error calling module function 

Error: java.io.FileNotFoundException: app/testdb.db
    android.content.res.AssetManager.openAsset(Native Method)
    android.content.res.AssetManager.open(AssetManager.java:316)
    android.content.res.AssetManager.open(AssetManager.java:290)
    com.tns.NativeScriptActivity.getMethodOverrides(Native Method)
    com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:1567)
    android.app.Activity.performCreate(Activity.java:5133)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
    android.app.ActivityThread.access$600(ActivityThread.java:141)
    android.app.ActivityThread$H.handleM

![image](https://cloud.githubusercontent.com/assets/5836130/17836775/b93937fc-67bb-11e6-967f-3004116b0bcd.png)

can any one please help me.
May be I misunderstood the concept of copyingDatabase

Thanks In Advance

**Comment by NathanaelA** [comment]
Did you rebuild the app afterwords?   If you were doing a livesync; this won't work properly as livesync won't sync the database file over; so you need to do a rebuild of the app to get the db onto the device/emulator.

**Comment by NathanaelA** [comment]
Closed due to inactivity.  Please comment if you have any more issues with this.

**Comment by derKuba** [comment]
i had the same issue, after renaming my .db file. just ran
tns build [android/ios]

and everything is fine!

**Comment by toeknee581** [comment]
I had the same problem.  I added the .db file and livesync reported that it transferred the file.  I killed the livesync process (ctrl+c), did a tns build android, then tns run android and then it worked as expected.  Thanks @derKuba !
