### ISSUE TITLE
Unable to call methods inside of the sqlite constructor calback

### ISSUE THREAD

**Issue by venkateshprasad** [NathanaelA/nativescript-sqlite#29]
I am able to query the sqlite . But inside of constructor call back i am unable to call my service or component methods and Unable to access any variable that is in class. It is raising any error it just stops the execution .

getAll(){
        new Sqlite("MyTable",(err, db) => {
            if (err) {
            console.error("We failed to open database", err);
            } else {
                db.all('select * from person',function(err, resultSet) {
                    alert("Row of data was: "+resultSet);
                    //Below add method is in service
                 this.todoStore.add("Enter Name", false,null,'','',true,null);
                  //
                 alert("working");
                });
            }
        });
    }

**Comment by NathanaelA** [comment]
1. You would have to look that the code that TS generated; but "this" might be pointing to the wrong "this"....   
2. You might also try adding the error promise to see what the actual error is...

**Comment by venkateshprasad** [comment]
Thank you @NathanaelA
