### ISSUE TITLE
NSFileManager.defaultManager is not a method

### ISSUE THREAD

**Issue by stefalda** [NathanaelA/nativescript-sqlite#30]
Hi,
 I've installed the plugin but working with iOS10 (I've not tested with previous versions of the SDK) I got an error stating that defaultManager is not a function but a property of NSFileManager:

[https://developer.apple.com/reference/foundation/nsfilemanager/1855948-defaultmanager?language=objc](Objective-C definition
)

The Objective-C code is
`NSFileManager *fileManager = [NSFileManager defaultManager];`
so it worked as a function... maybe Apple has changed something in the latest release...

Deleting the parenthesis the code works, but I think you'll have to modify the source code.

**Comment by NathanaelA** [comment]
XCode 8 changed how to access some things, been a pain.   Thanks for letting me know that sqlite has one of them that needs to be fixed...

**Comment by NathanaelA** [comment]
It should be fixed for iOS now on v1.1.2
