### ISSUE TITLE
[feature] add option ENABLE_WRITE_AHEAD_LOGGING

### ISSUE THREAD

**Issue by kazemihabib** [NathanaelA/nativescript-sqlite#39]
please add option for https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#ENABLE_WRITE_AHEAD_LOGGING

**Comment by NathanaelA** [comment]
The ability to set the open flags will show up in a future version.     But it is not a high priority as my contract/freelance work has a higher priority over free work.

**Comment by NathanaelA** [comment]
The newest version allows you to pass flags in options to the constructor.
