### ISSUE TITLE
 Cannot build project because module nativescript-sqlite contains insecure code

### ISSUE THREAD

**Issue by tangrl** [NathanaelA/nativescript-sqlite#4]
After I added NativeScript-Sqlite plug-in to Telerik AppBuilder project, I got "Cannot build project because module nativescript-sqlite contains insecure code. Remove the module and try again." when building an iOS App package. It works for Android build.
Any idea why I'm getting the error?

Thanks!

Richard

**Comment by NathanaelA** [comment]
I have no idea why you would be getting that error; I have pushed a support request to Telerik about it to see if we can get some idea what is wrong.

**Comment by teobugslayer** [comment]
Hi @tangrl,

A Telerik AppBuilder dev here.

Thank you for mentioning this issue! 
This was an omission in our build infrastructure. We have ensured that the sqlite plugin can be added to a project. Please try again and tell us if you had any problems.

**Comment by tangrl** [comment]
It works now. 

Thanks!
