### ISSUE TITLE
there is no example project in given link

### ISSUE THREAD

**Issue by isuruAb** [NathanaelA/nativescript-sqlite#45]
https://github.com/NathanaelA/nativescript-sqlite-example this gives 404 error

**Comment by NathanaelA** [comment]
The demo is now included in this repo in the demo folder...   Where are you seeing this link to the old -example repo.

**Comment by NathanaelA** [comment]
I could have sworn I updated the readme...  It has been updated...

**Comment by isuruAb** [comment]
<img width="955" alt="screen shot 2017-04-25 at 11 11 03 am" src="https://cloud.githubusercontent.com/assets/7692626/25370376/f3f6ff74-29a7-11e7-9dc6-7f37da87cce7.png">

Here in this repo's readme file
