### ISSUE TITLE
Transactions not working on ios (commercial version)

### ISSUE THREAD

**Issue by tcione** [NathanaelA/nativescript-sqlite#47]
Hey, I was facing a bug when trying to start transactions on iOS. Managed to fix it adding "this._transactions = [];" on line 51 to the sqlite.ios.js file.

(my package version is 1.1.5)

Decided to post here, in case it helps :)

**Comment by NathanaelA** [comment]
@tcione - Thanks for the fix.   I'll get this in the latest version.  :-D

**Comment by NathanaelA** [comment]
Fixed in latest version.  You should have an email to the link for it if you need it...  :grinning:
