### ISSUE TITLE
how to handle image in iOS

### ISSUE THREAD

**Issue by pap5508** [NathanaelA/nativescript-sqlite#48]
I am receiving Image base64 content in Response from the Server... I am handling as below,

```
// assign base64 content to Imagesource
  var image = new ImageSource();
  image.loadFromBase64(getImageData[0].Image.File);
```

Now I would like to Implement to Store image in SQLIte
Sqlite only supports BLOB . 

Base64 to BLOB file save in SQLIte

To convert base64 to BLOB i have used (NOT WORKING)
```
 var blob = this.b64toBlob(getImageData[0].Image.File);
 console.log("blob data: " + blob);*/
```

How to save and retrieve BLOB Image from Database and set to Image-Source ?

**Comment by NathanaelA** [comment]
Well, blob is normally binary; you don't use base64.    If you want to use base64 then just use a string in SQLite.

**Comment by pap5508** [comment]
@NathanaelA : Thank you for your help and time.
