### ISSUE TITLE
Error: Module "nativescript-sqlite" not found.

### ISSUE THREAD

**Issue by imranrafiq01** [NathanaelA/nativescript-sqlite#5]
I have reference the Nativescript Sqlite in my file like that var Sqlite = require( "nativescript-sqlite" );
After build from Telerik Appbuilder application loads without any issue but when live sync the changes got the error mentioned above. If I remove the Sqlite reference it works fine. Checking on android. Any help.

**Comment by NathanaelA** [comment]
Can you try again, and also make sure your NativeScript version is set to v1.5.   According to Telerik it is a valid plugin on the AppBuilder platform.

**Comment by ligaz** [comment]
@imranrafiq01 Please note that this plugin is currently not available in NativeScript companion app so you will have to do real builds in order to use it. We will include it in one of the future updates of the companion app.

**Comment by imranrafiq01** [comment]
Thanks for the information @ligaz. 
Yes u r right because on live sync in Telerik companion app it is not working, otherwise working fine when build on first time.
