### ISSUE TITLE
Can't find variable: sqlite3_open_v2

### ISSUE THREAD

**Issue by jibon57** [NathanaelA/nativescript-sqlite#50]
Hello,

Thanks for the plugin. This is working fine with Android but having problem with IOS.
```

CONSOLE ERROR file:///app/services/commonServices.js:20:30: We failed to open database ReferenceError: Can't find variable: sqlite3_open_v2
CONSOLE LOG file:///app/services/commonServices.js:21:28: null
CONSOLE ERROR file:///app/tns_modules/@angular/core/./bundles/core.umd.js:1091:24: ERROR Error: Uncaught (in promise): ReferenceError: Can't find variable: sqlite3_open_v2

```
What I did so far:
```
Delete the app off the phone.
tns platform clean ios
tns run ios
```
My Code:
```
new Sqlite("mydb.db", function(err, db) {
      if (err) {
        console.error("We failed to open database", err);

      } 
```
MacOS: 10.12.5 (16F73)
Xcode: Version 8.3.2 (8E2002)
NativeScript: 3.0.1

**Comment by jibon57** [comment]
Anyone can help me on this issue please?

**Comment by NathanaelA** [comment]
1. Verify the plugin exists in the node_modules folder.
2. Try do to another `tns platform clean ios`

Try it again.  The clean will normally fix the issue; but if the plugin isn't installed correctly the clean won't do anything...

**Comment by jibon57** [comment]
@NathanaelA Thanks for reply. Yes, I am trying it but don't know not working. I think the folder exsist under "node_modules".

https://prnt.sc/fg6ow5
https://prnt.sc/fg6ozi

I tried to clean platform several time but still no luck :( 

`CONSOLE ERROR file:///app/services/commonServices.js:20:30: We failed to open database ReferenceError: Can't find variable: sqlite3_open_v2
`

**Comment by jibon57** [comment]
@NathanaelA Any further suggestions?

**Comment by NathanaelA** [comment]
@jibon57 - Off the top of my head no.   It is on my todo list to verify this works as-is on TNS 3.0; but I haven't had a chance to try it yet.

**Comment by jibon57** [comment]
@NathanaelA, Did you get time to test it?

**Comment by NathanaelA** [comment]
@jibon57 - It is on my list to do list to try out; but I only work on free stuff when my paid stuff is all done.

**Comment by NathanaelA** [comment]
@jibon57 - It works fine on my demo app.   I just pulled the latest from my repo; updated to NS 3.x for everything in the demo and then ran it fine on iOS.      I am not sure what you are doing wrong...

**Comment by jibon57** [comment]
@NathanaelA, Will you please share your MacOS's information? I tried your plugin from a fresh Nativescript angular js template. But getting same error there also.

**Comment by jibon57** [comment]
aha.. I got the problem... It was for the long path like described here: https://github.com/NathanaelA/nativescript-sqlite/issues/2#issuecomment-289174895

I moved the project to Desktop & ran. It's working now ....

**Comment by stevegardnersa** [comment]
I think it has to do with spaces in the path rather than the length. See my comment here [https://github.com/NathanaelA/nativescript-sqlite/issues/2#issuecomment-327161166](url)

**Comment by NathanaelA** [comment]
One more solution is to also delete the app from the phone before you do a rebuild of the app and re-run it.  A version of the APP on the phone can cause the new version to not be updated properly.
1. Delete App off phone
2. TNS platform clean ios
3. TNS run ios
