### ISSUE TITLE
Nativescript 3 support?

### ISSUE THREAD

**Issue by johnnyzen** [NathanaelA/nativescript-sqlite#51]
Hi there.

Any timeframes for support for Nativescript 3?

**Comment by NathanaelA** [comment]
Should already support NS 3 fine.   There was nothing in this plugin that needed changes to be compatible with NS3.

**Comment by johnnyzen** [comment]
many thanks :)

**Comment by NathanaelA** [comment]
Just to update this real quick; I have tested it on NS 3.x and it worked fine for me, and my test routine which tests the functionality worked properly, with no errors.   So yeah, this plugin should work fine on NS 2 & NS 3 w/o any issues.
