### ISSUE TITLE
too many sql variables

### ISSUE THREAD

**Issue by MehdiAroui** [NathanaelA/nativescript-sqlite#52]
Hey every one, thanks for that great plugin, I just have that problem "too many sql variables" I'd like if there is a way to change SQLITE_MAX_VARIABLE_NUMBER.
thanks

**Comment by NathanaelA** [comment]
@MehdiAroui -the only way to do this would be to compile your own version of the native sqlite drivers.  This plugin uses the built in sqlite that comes with the phone.
