### ISSUE TITLE
Sqlite.version throws an error when called without arguments

### ISSUE THREAD

**Issue by madakk** [NathanaelA/nativescript-sqlite#55]
When used without a callback to get a Promise, the function throws an error. In Android the error is:

`Error: java.lang.IllegalArgumentException: Cannot bind argument at index 1 because the index is out of range.  The statement has 0 parameters.`.

Presumably iOS has a similar error. This error is coming from Sqlite.get:

https://github.com/NathanaelA/nativescript-sqlite/blob/ad9d147ac82bd6494cd5fcf5e8b0f60d265045ab/sqlite.android.js#L510

The reason is that Sqlite.version, when called without arguments, calls Sqlite.get with the mode flag in the params argument:

https://github.com/NathanaelA/nativescript-sqlite/blob/ad9d147ac82bd6494cd5fcf5e8b0f60d265045ab/sqlite.android.js#L314

Which Sqlite.get fails to handle correctly.

**Comment by NathanaelA** [comment]
@madakk - Thanks for the nice bug report.  I see the issue, nice find.  👍

**Comment by NathanaelA** [comment]
Thank you this has been fixed in v1.1.9 @madakk
