### ISSUE TITLE
Tests for nativescript-sqlite without platform

### ISSUE THREAD

**Issue by cgebe** [NathanaelA/nativescript-sqlite#56]
I want to run tests without starting a device, e.g. an android platform. When i run my tests with nyc/mocha i get the following error: "Cannot find module 'nativescript-sqlite'". Is there a possibility to test the database without a platform?

**Comment by NathanaelA** [comment]
No the tests have to actually run on a device.

**Comment by cgebe** [comment]
Thank you.
