### ISSUE TITLE
Precision error when store in numeric column

### ISSUE THREAD

**Issue by isaacfi** [NathanaelA/nativescript-sqlite#58]
When I store in a numeric column, the value is wrong:

CREATE TABLE NumericTest(
  value NUMERIC)

INSERT INTO NumericTest VALUES(6.3)

When I retrieve data from NumericTest with db.all it gives me 6.300000190734863

**Comment by NathanaelA** [comment]
Floating point numbers in most programming languages include JavaScript are approximate values IEEE 754; a good article about this is: https://modernweb.com/what-every-javascript-developer-should-know-about-floating-points/

**Comment by NathanaelA** [comment]
I should probably say; there is two ways to store "exact" numbers.  
1. as a string.  So you store "6.3" rather than 6.3
2. As a whole number.   630 then you move the decimal point  two over when display it.  But all numbers are handled as whole numbers.
