### ISSUE TITLE
Cannot build/run/emulate on iOS

### ISSUE THREAD

**Issue by mikeres0** [NathanaelA/nativescript-sqlite#6]
If I try to run the build for an Android platform, there are no issues and all functionality is present. However, if I try to run on any iOS device I receive the following error:

john-thornewills-imac:nextra-test johnt$ tns emulate ios
Successfully prepared plugin nativescript-insomnia for ios.
Successfully prepared plugin nativescript-sqlite for ios.
Processing node_modules failed. Error: Command failed: /bin/sh -c ruby -e "require 'xcodeproj'; Xcodeproj::Config.new('/Users/johnt/Dropbox/NativeScript/nextra-test/platforms/ios/plugins-debug.xcconfig').merge(Xcodeproj::Config.new('/Users/johnt/Dropbox/NativeScript/nextra-test/node_modules/nativescript-sqlite/platforms/ios/build.xcconfig')).save_as(Pathname.new('/Users/johnt/Dropbox/NativeScript/nextra-test/platforms/ios/plugins-debug.xcconfig'))"
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- xcodeproj (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'

Any ideas folks?

**Comment by mikeres0** [comment]
I found the issue. I didn't have the correct `gem` installed.

You can install is using `sudo gem install xcodeproj`

**Comment by NathanaelA** [comment]
Hmm, that is a new one.  I've installed this many times on my box and never seen that happen.  I'm glad you have found the solution!
