### ISSUE TITLE
Keep database file between app reinstallations

### ISSUE THREAD

**Issue by dhabierre** [NathanaelA/nativescript-sqlite#63]
Hi.

I'm using sqlite in a NS app.

When I uninstall the app (to install next dev-version), the database file is also deleted.
I'd like to know if there is a way in order to keep the database.

What about updates from the Google Store once the app is published?

Thanks.

**Comment by NathanaelA** [comment]
Updates shouldn't delete the database.  De-installs will, as that is normally what you want when the app is no longer present.   If you need to keep the database, then you have to copy the db out of the app folder and into the shared storage.

**Comment by Universi** [comment]
Hi,
I also get this problem that I did not have with another application.
When I increment the version of my app, the existing database is deleted, while the app is still installed (not deleted from my device).

However, I have this code :
```
if(!Sqlite.exists(this._dbname_user)) {     
     
           Sqlite.copyDatabase(this._dbname_user);
}
```
You said : "If you need to keep the database, then you have to copy the db out of the app folder and into the shared storage"

Can you tell me how to do that, please?

**Comment by NathanaelA** [comment]
The above code you list should put the database in the application's database folder. 

Upgrading the application should not delete the existing database.    However, if you de-install your app and then install the app; the database will be deleted.
