### ISSUE TITLE
Sqlite.copyDatabase views in database are lost.

### ISSUE THREAD

**Issue by JohanCuello** [NathanaelA/nativescript-sqlite#64]
I just created a database with views definitions and copy in the app folder, but when I execute the Sqlite.copyDatabase the view definitions are not included in the copy. Is this an error of the method or the Sqlite database? I'm stuck with this, please help!.

**Comment by NathanaelA** [comment]
I'm afraid I have never messed with SQLite Views, so I don't know the answer for sure.  But if they were saved to the database they should still be their when copied to the phone.  Is it possible you are using a older version on the phone?

**Comment by JohanCuello** [comment]
You are right, for some reason the database file wasnt updated. After running tns run android --clean. The database file was updated.

Thanks
