### ISSUE TITLE
Multiple Insert

### ISSUE THREAD

**Issue by LorenDorez** [NathanaelA/nativescript-sqlite#65]
What is the best way to handle insert multiple records? I have a function that goes out and gets the records from an api and then need to insert them into the DB.

Would a foreach loop calling execSql() be the best way to handle this? 

Also note i use the promise setup for i need to be able to track when it finished

**Comment by NathanaelA** [comment]
Actually, using the all new Prepared statements in a transaction is the fastest way; you can actually pass the prepared statement .execute() an array of arrays.  i.e. `[ [ value1, value2, value3 ], [value1, value2, value3] ... ]` when the execute is all done, the single promise will be fulfilled.
