### ISSUE TITLE
Failed resolving method openOrCreateDatabase

### ISSUE THREAD

**Issue by leocrawf** [NathanaelA/nativescript-sqlite#66]
All worked well from the first day until today I got this. Every attempt to fix it has failed. I rename,  removed and recreated database, removed and added plugin again but still got this: 

SQLITE.CONSTRUCTOR -  Open DB Error Error: java.lang.Exception: Failed resolving method openOrCreateDatabase on class android.database.sqlite.SQLiteDatabase.
 com.tns.Runtime.resolveMethodOverload(Runtime.java:1045)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:953)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:937)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:929)
JS:     com.tns.FragmentClass.onCreateView(FragmentClass.java:35)
JS:     android.app.Fragment.performCreateView(Fragment.java:1700)
JS:     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
JS:     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
JS:     android.app.BackStackRecord.run(BackStackRecord.java:684)
JS:     android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
JS:     android.app.FragmentManagerImpl$1.run(FragmentManager.java:443)
JS:     android.os.Handler.handleCallback(Handler.java:733)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:136)
JS:     android.app.ActivityThread.main(ActivityThread.java:5017)
JS:     java.lang.reflect.Method.invokeNative(Native Method)
JS:     java.lang.reflect.Method.invoke(Method.java:515)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
JS:     dalvik.system.NativeStart.main(Native Method)

 I even pulled down a working version of the app from git and got the same error. Any idea how this can be resolved.

**Comment by NathanaelA** [comment]
Thank you for your report, some major changes to allow encryption caused a internal breaking change, in the Open source version.  Which I didn't catch in any of my tests that tested since I was testing all the new commercial/encryption stuff; but didn't test the non-encrypted db support.  

This is now fixed in 2.01     :grinning:

**Comment by leocrawf** [comment]
Thank you.
