### ISSUE TITLE
Performance compared to Cordova Version

### ISSUE THREAD

**Issue by LorenDorez** [NathanaelA/nativescript-sqlite#67]
Hi,

Im new to Nativescript and the emulators so this might be an issue with the emulators. Im converting a Cordova Project over to Nativescript and i noticed that the bulk inserts seem to take a bit longer than they did on the Cordova Sqlite plugin. Again not sure if its just the emulators. Im using the db.Prepare setup.

Does the db.execute run right away? wouldnt it be better to batch execute the inserts?

**Comment by NathanaelA** [comment]
You can start a transaction, then do the prepared.execute and finally do the db.commit and you should have better performance.    Doing db.prepare; then prepare.execute will fire each one separately.    In addition, if you batch together your inserts, i.e. prepare.execute([[insert 1], [insert2], [insert3]]); <--  I.E. pass in an array of arrays; it will be faster also.    

So in summary; first use a transactions to wrap it up
Second, send multiple rows at the same time.
