### ISSUE TITLE
Questions: Does this run in main UI Thread?

### ISSUE THREAD

**Issue by LorenDorez** [NathanaelA/nativescript-sqlite#70]
Does this run on the main UI thread?

I am trying to implement a loading screen for long running db tasks using the following plugin
https://github.com/NathanWalker/nativescript-loading-indicator

However, when i try to loader only shows/flicks at the end of the Database options. Example code below

```
global.dialogs.confirm(`Are you sure you want to perform the following action "${args.object.command}"?`)
            .then((result) => {
                if (result) {
                    const commandName = args.object.command;
                    console.log(`Running Command ${commandName}`);
                    global.loader.show();
                    global.oversii.db[commandName]()
                        .then((results) => {
                            global.dialogs.alert(`Successfully ran command "${commandName}`);
                            global.loader.hide();
                        })
                        .catch((error) => {
                            global.loader.hide();
                        });
                }
            });
```

**Comment by NathanaelA** [comment]
Everything in NativeScript runs on the main thread; unless you specifically move it to its own thread.   One of the coming features in the commercial version is SQLite on a background thread automatically so you don't have to do that.

**Comment by LorenDorez** [comment]
Because if i add something like a fetch() then call ad db operation my loading indicator shows up just fine. But not when i call my db operaton first

**Comment by NathanaelA** [comment]
Yep, everything runs on the main thread, unless you move it.  Depending on what calls are done when, will decide when a element will show up.
