### ISSUE TITLE
[REQUEST] typescript definition for free version

### ISSUE THREAD

**Issue by gimox** [NathanaelA/nativescript-sqlite#72]
first, thanks for your work. 
second, we need the TypeScript definitions for use in angular 5 with aot, or this plugin is a nightmare, please  add this to the free version.

**Comment by NathanaelA** [comment]
I am a huge open source supporter; I have well over 30 plugins that I have created for NativeScript alone;   However, do you have any idea how much money has been donated to me via Paypal or Patreon, to show any appreciation for all this hard work?   Most people get paid to write apps; it would be nice if the community also helped out the plugin/open source authors with some financial support occasionally.

If you find it a nightmare; then please pay for a commercial copy and get the typings...    The commercial versions helps fund them, and says you **appreciate** the hard work that went into making a stable usable plugin, and the amount of time savings the whole package gives you.
