### ISSUE TITLE
SQLITE.CONSTRUCTOR -  Open DB Error Error: java.lang.Exception: Failed resolving method openOrCreateDatabase on class android.database.sqlite.SQLiteDatabase

### ISSUE THREAD

**Issue by kefahB** [NathanaelA/nativescript-sqlite#74]
Hello,

I have this error code that appears with android only, but everything goes well in ios!

`JS: SQLITE.CONSTRUCTOR -  Open DB Error Error: java.lang.Exception: Failed resolving method openOrCreateDatabase on class android.database.sqlite.SQLiteDatabase
JS:     com.tns.Runtime.resolveMethodOverload(Runtime.java:1049)
JS:     com.tns.Runtime.runModule(Native Method)
JS:     com.tns.Runtime.runModule(Runtime.java:530)
JS:     com.tns.Runtime.run(Runtime.java:522)
JS:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
JS:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
JS:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
JS:     android.app.ActivityThread.-wrap1(ActivityThread.java)
JS:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
JS:     android.os.Handler.dispatchMessage(Handler.java:102)
JS:     android.os.Looper.loop(Looper.java:148)
JS:     android.app.ActivityThread.main(ActivityThread.java:5417)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

```
new Sqlite("test.sqlite", function(err, db) {
    if (err) 
    {
	    console.log(err, err.stack);
    }
    db.execSQL("CREATE TABLE IF NOT EXISTS bibliotheque (id INTEGER PRIMARY KEY ASC, ....)", [], function(err) {
        console.log("TABLE CREATED");
    }); 

    db.execSQL("CREATE TABLE IF NOT EXISTS tracks (id INTEGER PRIMARY KEY ASC, ...., title VARCHAR(255), duration VARCHAR(255))", [], function(err) {
        console.log("TABLE CREATED");
    }); 
});
```

```
sqlite3 --version
3.19.3 2017-06-27 16:48:08 2b0954060fe10d6de6d479287dd88890f1bef6cc1beca11bc6cdb79f72e2377b
```

I tested with API 23 and 27 and still the same error !

Thank you

**Comment by kefahB** [comment]
I remove and reinstall Nativescript-sqlite an is work now !

**Comment by ryanzaatari** [comment]
Thank you @kefahB that resolved the issue indeed
