### ISSUE TITLE
{"__zone_symbol__state":null,"__zone_symbol__value":[]}

### ISSUE THREAD

**Issue by sarvagayatri** [NathanaelA/nativescript-sqlite#76]
i have written db.get(query), where it not returning any rows as my query param meeting rows does;t exist in the database. 
i am returning like return row && row[1] || null. 
as row[1] is the value required. but its returning value as [object object] , 
JSON.Stringify giving as {"__zone_symbol__state":null,"__zone_symbol__value":[]}. 
how to return result as null to my calling page.

**Comment by NathanaelA** [comment]
I would have to see the source code to be able to duplicate this issue.  I'll happily reopen if you can give me a case to duplicate this issue.
