### ISSUE TITLE
Transactions in iOS Simulator not Working (Commercial)

### ISSUE THREAD

**Issue by isaacfi** [NathanaelA/nativescript-sqlite#77]
I'm trying to insert a list of items, beginning a transaction, and it works for android, but for iOS I have a problem. This is the code:

The Interface for Query Item:

```
interface QueryItem {
    query: string;
    values: Array<any>;
}
```

```
let queryArray = new Array<QueryItem>();
**I ADD ITEMS TO THE LIST HERE
return new Promise<any>((onSuccess, onError) => {
            this.sqliteInstance.dbPromise.then(db => {
                db.begin().then(() => {
                    for (let queryItem of queryArray) {
                        db.execSQL(queryItem.query, queryItem.values).then(id => {
                                console.log("Saved ID: " + id);
                        }, error => {
                            console.log(error);
                            db.rollback().then(() => {
                                onError();
                            }, onError);
                        });
                    }
                    return db.commit().then(() => {
                        onSuccess();
                    }, onError);
                })

            });
        });
```

The error shows this:

CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:1389:24: ERROR Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'this._transactions.length')

**Comment by NathanaelA** [comment]
I just re-tested the demo on the latest version of NativeScript.  And it passed all tests.    You can type "test" in the add name box and it will run a set of tests that test each of the pieces of functionality.   Transactions are still passing on iOS.   

I'm using:
- NativeScript-Sqlite - v2.0.1
- NativeScript-Sqlite-Encrypted-v1.0.0
- NativeScript-Sqlite-Commercial-v1.0.0

I noticed in your code something; 
` this.sqliteInstance.dbPromise.then(db => {`
How does this return a valid db instance...  Maybe your db instance is invalid someway.

**Comment by isaacfi** [comment]
Hi Nathan,

Thank's for your answer, the db instance is valid, but the nativescript sqlite that I have installed is:
nativescript-sqlite-commercial": "file:nativescript-sqlite-commercial-1.1.5.tgz"

Can you tell me, how to do the right installation? I'm interested in enable the encryption feature.

Regards.

**Comment by NathanaelA** [comment]
Ah, that will do it; that is an old version of sqlite -- I completely redid the new version to be much easier to support and keep in sync -- it does look like I was an idiot and used the wrong version when I released the new commercial version.

You want to download the 2.00 link I sent you; it has the NEW commercial and encryption libraries in it.
I recommend you extract them to a folder called "plugins" in your main application folder.
Then the steps to upgrade and use the latest is:

`tns plugin remove nativescript-sqlite-commercial`
`tns plugin remove nativescript-sqlite`
`tns plugin add nativescript-sqlite@latest`
`tns plugin add plugins/nativescript-sqlite-commercial-1.0.0.tgz`
`tns plugin add plugins/nativescript-sqlite-encrypted-1.0.0.tgz`

This should give you the latest of everything.  To enable encryption; you just need to set a key on the database; the docs (& demo) on both the private repo and in the plugin should give you the example on how to easily enable encryption.

**Comment by isaacfi** [comment]
Tnx Nathan, this works like a charm
