### ISSUE TITLE
JS: SQLITE.CONSTRUCTOR    Failed resolving method openOrCreateDatabase on class android.database.sqlite.SQLiteDatabase Error while opening the app

### ISSUE THREAD

**Issue by VivekmanikandanD** [NathanaelA/nativescript-sqlite#80]
java.lang.Exception: Failed resolving method openOrCreateDatabase on class android.database.sqlite.SQLiteDatabase
The above error comes in command prompt while debugging the app, Can anyone tell what will be the issue and the necessary steps to prevent this

**Comment by stoanarrr** [comment]
"tns plugin remove nativescript-sqlite"
and then "tns add nativescript-sqlite" solved the problem for me

**Comment by davorpeic** [comment]
It is `tns **plugin** add nativescript-sqlite` and it fixed my issue too.
