### ISSUE TITLE
Recurring error message with Prepared Statement : SQLITE.PrepareExecute Failed

### ISSUE THREAD

**Issue by Universi** [NathanaelA/nativescript-sqlite#81]
Hi,

I'm using Prepared Statement to pass an Array of Arrays, but half the time, I get this error message `Insert err SQLITE.PrepareExecute Failed 20 undefined`.

The error seems to occur more often in the simulator than on the device.

I have an array of 92 arrays  (each has 23 values) : `allItems_arr`

This is my code :

```
try {

                console.log("!------------- Create Prepared Items ");
                var prepared = self._db.prepare("INSERT INTO Item (id, user_id, name_item, name_wa, is_action, matiere, fonct_gram, genre, feminin, nombre, type_picto, url_anim0, url_photo, url_fig0, url_symb0, url_video, url_audio0, record_active, has_record, marginZoom, active, locked, nb_used) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);");
                
                self._db.begin();
                prepared.execute(allItems_arr, function(err) {
                    if (err) {             
                        console.log("!---- Insert err", err, err && err.stack);
                        return;
                    }
                    self._db.commit();
                    
                    prepared.finished();
                    console.log("!------------- Prepared Items finished ");
                    callback();
                });
            
  } catch(err) {
       console.log("Error creating prepare data", err);
  }
```

**Comment by NathanaelA** [comment]
Error 20 - (20) SQLITE_MISMATCH
https://sqlite.org/rescode.html

Probably something in your array data is messed up...

**Comment by Universi** [comment]
@NathanaelA, I thank you so much.

I forced the creation of the id of the prepared items, which I wanted to be the same as the original database. What would not be possible?
Leaving Sqlite create automatically, the error no longer occurs.

**Comment by NathanaelA** [comment]
Could be maybe a duplicate id, assuming that column is a key it wouldn't allow any duplicate keys...   Without having the actual data in front of me, I can only guess...
