### ISSUE TITLE
Webpack bundle issues with sqlite

### ISSUE THREAD

**Issue by leocrawf** [NathanaelA/nativescript-sqlite#84]
After following the docs found here: https://docs.nativescript.org/best-practices/bundling-with-webpack#bundling  and using the command: tns run android --bundle with nativescript 3.4.3 in an effort to reap the rich benefits of webpack, I am left with this warning during the building process:

WARNING in ../node_modules/nativescript-sqlite/sqlite.js
940:18-30 Critical dependency: the request of a dependency is an expression
 @ ../node_modules/nativescript-sqlite/sqlite.js
 @ ./bundle-config.js
 @ ./app.js

Also when the app runs and I try to navigate to the first page using the database I get this error:
Error: java.io.FileNotFoundException: app/KWL_MOVILE_25_db.sqlite. In the  the bundle.config file I have: global.registerModule("nativescript-sqlite",() => require("../node_modules/nativescript-sqlite")); 

Is there a reason why this would not work? Everything worked well until I try to bundle.

**Comment by spmamidi** [comment]
+1

**Comment by leocrawf** [comment]
Through some more checking around I discovered that I have to import additional files using the following webpack config:
    
 new CopyWebpackPlugin([
                { from: "App_Resources/**" },
                { from: "fonts/**" },
                { from: "**/*.jpg" },
                { from: "**/*.png" },
                { from: "**/*.xml" },
                { from: "/*.sqlite" },
            ]),
however I am still not getting the file. The same error is occurring.

**Comment by leocrawf** [comment]
I found the fix. { from: "**/*.sqlite" }.
