### ISSUE TITLE
Connecting to remote db (not internal memory db)

### ISSUE THREAD

**Issue by webleaf** [NathanaelA/nativescript-sqlite#85]
Is it possible to connect to remote db? I need possibility in parallel connection to db with some GUI, for more comfortable debugging. I need to see how data change after every query.

**Comment by NathanaelA** [comment]
SQLite can't connect to a remote DB; but there are many ways you can do it.
1. You can use your own API to send changes to a server you control.
2. You can use something like CouchBase to store the remote changes.
3. You can use firebase to store the remote changes.
