### ISSUE TITLE
Running app with nativescript-sqlite on 32bit hardware

### ISSUE THREAD

**Issue by darxmac** [NathanaelA/nativescript-sqlite#87]
Running our app on 32bit hardware triggers the following error:

```
Metadata for "sqlitewrapper.sqlitehelper" found but symbol not available at runtime
```

is that a known limitation, or is there a trick to get it working ?

![image1](https://user-images.githubusercontent.com/139267/39748176-bcbc5360-52af-11e8-9801-0cd6d412546d.PNG)

**Comment by NathanaelA** [comment]
Well, now that is very interesting.  There is a couple things I can do to see if we can fix this as I've seen this error in a few different plugins over the years.  ;-)

1. Is this under NativeScript 4.0 or 3.0?
2. I assume this is when trying to create a release iOS application.

Just to set expectations; unless you are a paid user of the plugin, my paid contract work has a much higher priority over the free plugin work.   I do have a couple client projects in my queue that will need to get done before I will have a chance to look into what is causing the issue in the plugin.

**Comment by darxmac** [comment]
1. This is Nativescript 4
2. This is running the app built as release on an iPad 4th Gen

**Comment by darxmac** [comment]
digging around a bit, looks like the sqlitewrapper.framework is built against arm64 only ?

![mlh-app____desktop_local_repos_mlh-app__-_____node_modules_nativescript-sqlite_platforms_ios_sqlitewrapper_framework_info_plist](https://user-images.githubusercontent.com/139267/39810739-7368aa60-5386-11e8-866b-62b614f865bc.png)

**Comment by NathanaelA** [comment]
Ah, I figured out why the 32 bit support wasn't built in, silly XCode messed it up.   So the next release when I have a few minutes to package everything up will have the fixed library...

![image](https://user-images.githubusercontent.com/850871/39812732-6eff5c4a-5353-11e8-94e4-3b235ffa1ea3.png)

**Comment by LorenDorez** [comment]
@NathanaelA 
I too am getting this error all of a sudden. I am a paid user of the plugin so when you get this fixed please let me know as right now it wont load on iOS devices

here my error from Nativescript Sidekick Console
```
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x8120f3 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x83a4c7 -[TNSRuntime executeModule:referredBy:]
3   0x7216f
4   0x1aac24eb <redacted>
JavaScript stack trace:
1   anonymous@file:///app/tns_modules/nativescript-sqlite/sqlite.js:20:29
2   evaluate@[native code]
3   moduleEvaluation@[native code]
4   @[native code]
5   promiseReactionJob@[native code]
6   require@[native code]
7   anonymous@file:///app/shared/oversii/db.js:1:93
8   evaluate@[native code]
9   moduleEvaluation@[native code]
10  @[native code]
11  promiseReactionJob@[native code]
12  require@[native code]
13  anonymous@file:///app/shared/oversii.js:3:19
14  evaluate@[native code]
15  moduleEvaluation@[native code]
16  @[native code]
17  promiseReactionJob@[native code]
18  require@[native code]
19  anonymous@file:///app/app.js:19:24
20  evaluate@[native code]
21  moduleEvaluation@[native code]
22  @[native code]
23  promiseReactionJob@[native code]
JavaScript error:
file:///app/tns_modules/nativescript-sqlite/sqlite.js:20:29: JS ERROR ReferenceError: Metadata for "sqlitewrapper.sqlitehelper" found but symbol not available at runtime.

```

**Comment by NathanaelA** [comment]
I have a fixed test version for those who are purchased users that should fix the issue; I'll send you the link via a private message. 

  For those looking for the open source version fixes; I believe I'll have a public release later towards the end of the month; I still have to do the final testing to do before I release it; and open source is a low priority compared to; well those who pay me.  :grinning:

**Comment by darxmac** [comment]
Hi,

Did you have time to release the opensource version of the plugin ?

**Comment by NathanaelA** [comment]
@darxmac - I have finished the testing and migrated the demo app to NS 4.x to make sure it still works for the current versions of NS.   All tests both opensource and commercial/encrypted are working on both iOS and Android under NS 4.x
