### ISSUE TITLE
Getting Error 1 when calling db.all

### ISSUE THREAD

**Issue by Daxito** [NathanaelA/nativescript-sqlite#9]
Hi,
I keep getting this error when trying to execute a select statement, do you know what it means by any chance?

Thanks

**Comment by NathanaelA** [comment]
Error 1 is general error or missing database.    
Are you sure your SQL is correct?

**Comment by Daxito** [comment]
Yes. My query runs ok from this tool, I used this tool in order to create my tables and DB.

http://sqlitebrowser.org/

I will use your demo and replace your database with one database created using this tool to see what happens, I got this error on ios emulator.

**Comment by Daxito** [comment]
Ok so, yes, I had it wrong, I had my database under "app/AnotherFolder", my bad, I moved the DB to "App" and it works now, is there a way to move this DB into a different folder like that? or it has to be under "App" only?

Thanks!

**Comment by NathanaelA** [comment]
You can put it into another folder; but you really need to use the copyDatabase to move it to the proper place so that it will work properly on both Android and iOS.   The sql demo app shows how to do this.

**Comment by Daxito** [comment]
Understood, thank you sir!
