### ISSUE TITLE
Cannot set property '_isOpen' of undefined

### ISSUE THREAD

**Issue by LuisAlcaras** [NathanaelA/nativescript-sqlite#90]
ERROR Error: Uncaught (in promise): TypeError: Cannot set property **'_isOpen'** of undefined

Somebody can help me?

**Comment by LuisAlcaras** [comment]
Sorry! solved!

**Comment by avsb93** [comment]
@LuisAlcaras Even I am facing the same issue. Can you please suggest the fix?
