### ISSUE TITLE
iOS error - Can't find variable: sqlitehelper

### ISSUE THREAD

**Issue by vasilyzakharov** [NathanaelA/nativescript-sqlite#91]
Using nativescript playground and the app is working fine on Android but on iOS 11 - iPhone X gives and error: JavaScript error:
file:///app/nativescript-sqlite/sqlite.js:20:29: JS ERROR ReferenceError: Can't find variable: sqlitehelper

Can you please help?

**Comment by NathanaelA** [comment]
The progress playground has several limitations; one of them is that it doesn't support plugins with native code.   Sqlite on iOS is a compiled plugin...

**Comment by Universi** [comment]
Hi @NathanaelA,

I get the same error message after updating nativescript-sqlite@latest & nativescript-sqlite-commercial-1.2.0 (not in Playground) 

`file:///app/nativescript-sqlite/sqlite.js:20:29: JS ERROR ReferenceError: Can't find variable: sqlitehelper`
