### ISSUE TITLE
ReferenceError: Can't find variable: sqlitehelper

### ISSUE THREAD

**Issue by Universi** [NathanaelA/nativescript-sqlite#92]
Hi @NathanaelA,

I just upgraded the nativescript plugins - core and commercial plugins - to the latest versions.

But I get this message error : 
`file:///app/tns_modules/nativescript-sqlite/sqlite.js:20:29: JS ERROR ReferenceError: Can't find variable: sqlitehelper`

**Comment by NathanaelA** [comment]
Make sure you do the following:
``` 
tns plugin remove nativescript-sqlite
tns plugin add nativescript-sqlite@latest
tns platform clean ios
```
then run and you should be all set.

**Comment by Universi** [comment]
Sorry, I didn't clean the iOS platform.
Thanks!
