### ISSUE TITLE
How to use spatialite extension?

### ISSUE THREAD

**Issue by pattrawuth2530** [NathanaelA/nativescript-sqlite#93]
I am newbie of NativeScript, Can you recommend how to use spatialite extension? 
(from this link: [spatialite ](https://www.gaia-gis.it/fossil/libspatialite/index) )

**Comment by NathanaelA** [comment]
@pattrawuth2530 - To my knowledge nobody has created a plugin that supports Spatialite for NativeScript yet.   You can double check by going to https://plugins.nativescript.rocks and checking.     If you need someone to develop it for you; I can make you a quote to build it for you, just contact me via email.
