### ISSUE TITLE
Support for "marketingMode" flag

### ISSUE THREAD

**Issue by RinkalGohel** [NathanaelA/nativescript-sqlite#94]
Hi there!

Wanted to know whether your plugin will still be working fine if I add the flag of 'marketingMode' set to 'none' in package.json file, as mentioned in one of the blogs of NativeScript release?

Here is the link of the blog where the reference is made for the same: https://www.nativescript.org/blog/announcing-the-release-of-nativescript-3.2

Looking forward to an early reply. Thank you!

**Comment by NathanaelA** [comment]
I have not heard of any issues with using markingMode none with the plugin.
