### ISSUE TITLE
Is it possible to fetch db.each results by field name?

### ISSUE THREAD

**Issue by cdsaenz** [NathanaelA/nativescript-sqlite#95]
Hi! I'm going along with this query below. And there's no way apparently to pick up values by field name (row.req_name for example). It seems you just can do row[0], row[1] etc.. Is that so?  Any alternative? Thanks!

```
// select all records
    new sqlite("cacg.db", function(err, db) {
        db.each("SELECT req_cuit,req_name FROM req_mst ORDER BY id", [], function(err, row) {
            console.log(row);            
        });
    });
```

**Comment by NathanaelA** [comment]
Please read the docs; it has how to switch to field names rather than arrays.
