### ISSUE TITLE
Accessing the same database from main thread and from a worker thread

### ISSUE THREAD

**Issue by darxmac** [NathanaelA/nativescript-sqlite#96]
I'm updating some big datasets in background worker, but retrieve the data in the main Nativescript thread.

Sometimes it seems to fall over with Sqlite errors, are there any obvious things I'm missing with this kind of scenario ?

**Comment by NathanaelA** [comment]
@darxmac - Yeah, don't do it at all.  :grinning:    All SQLite access should be done on the exact same thread; open; read, write, save, close.  Choose a single thread and do all work on it.  Trying to use it in multiple threads will cause sqlite to fall over and crash.    This is a limitation of the native sqlite as implemented on the platforms, they aren't built with multithreaded support.

The commercial/encrypted version that uses its own compiled version of SQLite is thread safe; however again there are some limitations on what is cross threadable in the way of access.

**Comment by darxmac** [comment]
It still says `(Coming soon) Multi-threading` on the pro version, or is that no longer true ? Put it another way, would I be able to open a new connection from the worker to the same database with the pro version and avoid it falling over ?
